### ISSUE TITLE
Typo search?

### ISSUE THREAD

**Issue by Krystus** [matchish/laravel-scout-elasticsearch#103]
Algolia from the start allow for typo in search results. How can I set this in Scout Elasticsearch? It's something from elasticsearch config or I can manipulate it from Laravel config file?

I don't know how to name it exacly but I'm looking for something like searchable attributes configuration, ranking and sorting and typo tolerance.

**Comment by Krystus** [comment]
I think my question part about typo tolerance will be related to Fuzzy Query:
https://www.elastic.co/guide/en/elasticsearch/reference/5.3/query-dsl-fuzzy-query.html#query-dsl-fuzzy-query

Don't know tho where to start with it.

**Comment by matchish** [comment]
The fastest way to start is using `fuzzy` operator
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

```
$results = Book::search('elasticearch~1');
```
