### ISSUE TITLE
[Feature] how to use queue import many-to-many relationshop?

### ISSUE THREAD

**Issue by StringKe** [matchish/laravel-scout-elasticsearch#105]
**Is your feature request related to a problem? Please describe.**
I have a database table with many-to-many relationship `Materials (keywords) => TagsKey => Tag`
When I tried to import data into elasticsearch, it was not imported at all. I do n’t know if I am already processing the data or where I stopped.

If there is no relationship between these keywords, I have a total of 60k arrays, and all of them are imported in less than 60s. Many-to-many relationships are not completed in 30 minutes, and there is no data in kibana.

**Describe the solution you'd like**
can see what operations are being performed during the import, for example: the data with the id 1001 is being imported

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/31089228/77132389-37afd700-6a9a-11ea-954c-0837797a9185.png)
```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        // ElasticSearch 注入
        $this->app->bind(ImportSourceFactory::class, MaterialImport::class);
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
    }
}
```

```php
class MaterialModel extends Model
{

    use Searchable;
    protected $table = "materials";
    protected $appends = ['keywords'];

    public function getKeywordsAttribute()
    {
        return implode(' ', array_unique(array_filter($this->tags()->pluck('title')->toArray())));
    }

    public function tags()
    {
        return $this->belongsToMany(TagModel::class, MaterialTagModel::class, 'mid', 'tid');
    }

    public function searchableAs()
    {
        return 'materials';
    }
}
```
```php
final class MaterialImport implements ImportSourceFactory
{
    public static function from(string $className): ImportSource
    {
        return new DefaultImportSource($className, [new MaterialKeywordsScope()]);
    }
}
```php
class MaterialKeywordsScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $builder->with('tags');
    }
}
```

**Comment by StringKe** [comment]
![image](https://user-images.githubusercontent.com/31089228/77134240-0d154c80-6aa1-11ea-832e-3523d69ae176.png)
i try use redis queue import data , Completed in 0s

**Comment by matchish** [comment]
Do you have `toSearchableArray` method in your model? What is result of `$model->toArray()`?

**Comment by StringKe** [comment]
yep, but execution queue always fails

**Comment by StringKe** [comment]
![image](https://user-images.githubusercontent.com/31089228/77138808-60da6280-6aae-11ea-91ef-18c8494bf22e.png)
![image](https://user-images.githubusercontent.com/31089228/77138843-836c7b80-6aae-11ea-89e4-ffa3f1f24727.png)

**Comment by matchish** [comment]
This driver doesn't use `Laravel\Scout\Jobs\MakeSearchable` job

**Comment by StringKe** [comment]
I see `matchish/laravel-scout-elasticsearch` has a corresponding job. How to use it?

**Comment by matchish** [comment]
`php artisan scout:import`

**Comment by matchish** [comment]
https://github.com/matchish/laravel-scout-elasticsearch/blob/f2c00ec82ceb3b91aba8c2c8dc5e1b7456ac093b/src/Console/Commands/ImportCommand.php#L50

**Comment by StringKe** [comment]
config/scout.php => queue, Need to be set to `false`?

**Comment by matchish** [comment]
It can be `true` or `false`

**Comment by matchish** [comment]
I've found where `Laravel\Scout\Jobs\MakeSearchable` was pushed. 
I'll ask you to try this branch when it passes tests https://github.com/matchish/laravel-scout-elasticsearch/tree/debug-queue

**Comment by StringKe** [comment]
ok, thank you, waiting for your good news

**Comment by matchish** [comment]
@StringKe Could you try this branch? https://github.com/matchish/laravel-scout-elasticsearch/tree/debug-queue

**Comment by matchish** [comment]
@StringKe Have you fix the issue?

**Comment by StringKe** [comment]
Yes, I am using it. When will it be released?

**Comment by StringKe** [comment]
The search method needs to use query_string, how to modify the default generated query_string, I don't need it, I prefer to use json

**Comment by StringKe** [comment]
like this [https://github.com/babenkoivan/scout-elasticsearch-driver#search-rules](url)

**Comment by matchish** [comment]
> Yes, I am using it. When will it be released?

Already in master

**Comment by matchish** [comment]
> The search method needs to use query_string, how to modify the default generated query_string, I don't need it, I prefer to use json

You can find it in `README` https://github.com/matchish/laravel-scout-elasticsearch#search

Plz don't post here questions unrelated to the issue. Feel free to open a new issue, or ask on https://stackoverflow.com/questions/tagged/laravel-scout%20laravel%20elasticsearch if it's not an issue
