### ISSUE TITLE
[2.0] Unresolvable dependency resolving

### ISSUE THREAD

**Issue by dragonfire1119** [matchish/laravel-scout-elasticsearch#11]
With the new 2.0 release I was trying it out & I get this error:

```
Unresolvable dependency resolving [Parameter #0 [ <required> $retries ]] in class Elasticsearch\Transport
```

**Comment by dragonfire1119** [comment]
Got it forgot you where moving to the developer registering the service provider.

**Comment by vaishnavmhetre** [comment]
I didn't understand the solution. @dragonfire1119 Please tell me. I'm facing the same issue.

**Comment by matchish** [comment]
@vaishnavmhetre https://github.com/matchish/laravel-scout-elasticsearch/issues/30#issuecomment-507946070_

**Comment by vaishnavmhetre** [comment]
> @vaishnavmhetre [#30 (comment)](https://github.com/matchish/laravel-scout-elasticsearch/issues/30#issuecomment-507946070)_

Got it. I did it in the first place but unfortunately, it didn't work. The vendor publish command wasn't picking up the service provider (and tag 'config' henceforth). Although I reinstalled, cleared cache (faced this issue many times before with other packages too). Imported all the Service Providers (Scout, as well as ElasticServiceProvider). Then that worked.

It doesn't seem like your package issue and more of the Laravel cache issue as I've faced this situation with other packages irrespective of the OS distribution (Linux, Windows, Mac) and hardware (tried HP, Lenovo, Acer [Laptops/Desktops]) but maybe you can dig if you wish too on this situation.

Previously, my routes files used to cache and never update after the change in web/api.php, unless I run cache:clear, and then cache:clear would spit out red errors of non-serializable routes (the routes with closure). So then I had to Comment those routes, then cache:clear, then the things worked fluently for your package (and others too).

**Comment by matchish** [comment]
@vaishnavmhetre Probably the issue related to bootstrap/cache/packages.php bootstrap/cache/services.php files
