### ISSUE TITLE
how to set elasticsearch account and password?

### ISSUE THREAD

**Issue by Duohao** [matchish/laravel-scout-elasticsearch#110]
how to set elasticsearch account and password?

**Comment by matchish** [comment]
Istead of `Matchish\ElasticSearchServiceProvider` you have register your own service provider. https://github.com/matchish/laravel-scout-elasticsearch#rocket-installation
And config `\ElasticSearch\Client` there.

**Comment by ametad** [comment]
Eg. in your `\App\Providers\AppServiceProvider`:

```php
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        /*
         * Elasticsearch Scout implementation overrides
         */
        $this->app->bind(\Elasticsearch\Client::class, function () {
            return ClientBuilder::fromConfig(config('elasticsearch.client'));
        });
    }
```

Your config could look like:

```php
<?php

return [
    'client' => [
        'hosts' => explode(',', env('ELASTIC_HOSTS', '127.0.0.1:9200')),
        'SSLVerification' => env('ELASTIC_CERTIFICATE', true),
        'logger' => app('log'),
    ],

```

**Comment by ametad** [comment]
The account credentials are probably part of your host url, like this:

`https://user:sercret-pass@my-es-server.test:9200`
