### ISSUE TITLE
[Feature] Always use same scope when update model in ES 

### ISSUE THREAD

**Issue by ametad** [matchish/laravel-scout-elasticsearch#111]
**Is your feature request related to a problem? Please describe.**

With `scout:import` the model scopes can be set with `ImportSourceFactory`, so you know all related models are correctly indexed as well in your Elasticsearch (ES) as they can be eager loaded.

But when you do a `$model->save()` somewhere in your code (e.g controller action), you must be sure to ALSO eager load the correct relations you need te be indexed in ES. 

This means you have to take care of these scopes in multiple places.

Now you could say, just set the `with` attribute in your model, but then you have no control anymore of when you want tot eager load and when not. The `ImportSourceFactory` would also not be needed anymore! But this IS a nice feature to have more control of it all!

**Describe the solution you'd like**

When the model is indexed into ES, it can be configured (somehow) to always have the same relations eager loaded (amongst other things you'd like), to always have the same data indexed in ES.

**Describe alternatives you've considered**

In the `Searchable` trait there is a function perhaps helpful:

```
    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        return $this->toArray();
    }
```

This could be overridden in your model. But I am not sure it is the best place to manage eager loading... And also, what would be the purpose of `ImportSourceFactory` anyways?

**Additional context**

Perhaps this is more a question than a feature request. Anyhow, suggestions are welcome!

**Comment by matchish** [comment]
The idea of 'ImportSourceFactory' to remove 'eloquent' dependency. Not implemented yet

**Comment by matchish** [comment]
You can extend https://github.com/laravel/scout/blob/1c4b66c36c2d6fdf94a8b79e2fbb9f4b378a6e26/src/Searchable.php#L25 and add your global scope.

**Comment by ametad** [comment]
> '

**Comment by ametad** [comment]
> The idea of 'ImportSourceFactory' to remove 'eloquent' dependency. Not implemented yet

Did not know that, thank you for the clarification!

**Comment by ametad** [comment]
> You can extend https://github.com/laravel/scout/blob/1c4b66c36c2d6fdf94a8b79e2fbb9f4b378a6e26/src/Searchable.php#L25 and add your global scope.

(or override the trait in the model itself)

But this is not about Global Scopes, as in must be always applied. I need to be flexible to eager load relations in one place, and not eager load in another place.

But when it comes to *send a model to ES*, then I always want to eager load (and send along with the model data) the same relations. Because always the same data needs be indexed for the searches.

**Comment by ametad** [comment]
All I needed was already there, but I had no overview. Me writing down the questions I had gave me the overview.

This could be the simple answer:

```php
class Vacancy extends Model
{
    use Searchable,
        SoftDeletes;

// ...

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $with = [
            'branches',
            'client',
            'company',
            'education',
            'licenses',
            'recruiterProfile',
        ];
        $this->loadMissing($with);

        return $this->toArray();
    }
```

**Comment by matchish** [comment]
Great solution) Thanks! I'll add it to README

**Comment by matchish** [comment]
The last question how to combine logic from `toSearchableArray`  and `ImportSourceFactory` which  relations to load in one place
