### ISSUE TITLE
Ranking and sorting with elasticsearch

### ISSUE THREAD

**Issue by Krystus** [matchish/laravel-scout-elasticsearch#113]
I can't find any info about how to modificate sort on GET methods. I can configure it in config file but that only sort "database of my elasticsearch" not results. On GET requests I still get it in wrong order. I can make sort with CURL on terminal:

```
curl -X GET "localhost:9200/products/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "sort" : [
        { "stock" : {"order" : "desc"}},
	{ "priority" : {"order" : "desc"}},
        "_score"
    ],
    "query" : {
        "term" : { "name" : "marvel" }
    }
}'
```

How can I implement it from code perspective?

@matchish I find something like that in issues but no I have no idea how to make it work like that curl reguest.

```
Product::search($term, function($client, $body) {
//all the valuable logic ...
});
```

I'm trying to rebuilt ranking and sorting from my Algolia settings.

![Screenshot 2020-04-17 at 01 19 39](https://user-images.githubusercontent.com/15039636/79515658-8628a500-8049-11ea-93e1-7c93df5247be.png)

**Comment by matchish** [comment]
https://github.com/ongr-io/ElasticsearchDSL/issues/162
