### ISSUE TITLE
[Feature] Make it possible to extend classes

### ISSUE THREAD

**Issue by denitsa-cm** [matchish/laravel-scout-elasticsearch#114]
First, thank you for the great package!

I am dealing with multiple database schemas (multiple tenants), and I want to run the `scout:import` command on multiple connections. I would usually extend from the base `ImportCommand`, change my connections and call the parent to handle the rest.

However, the `ImportCommand` class is `final` and I cannot extend it.

Is there any particular reason why the class is final?

I ended up making a custom command `scout:import-tenant` that internally calls the package's command. But it would be nice if I could just extend the command, add my options and call the parent.

**Comment by matchish** [comment]
Hello) Thanks for good question and kind words!
The reason for classes to be final is I don't think It's good idea to extend third party classes. Of course some times it have a place, sometimes no advantages in it but in general I make them final at first. Also I want to know what is the case to extend a class. Then I can to redesign the package to improve it.

In this case you can create a new command and call `ImportCommand` from the code. Does it solve your issue?

**Comment by denitsa-cm** [comment]
Hey @matchish 

I was tinkering with this yesterday and I realize my use case is a bit more complex and I won't be able to use the `ImportCommand` out of the box anyways.

My use case is:

We have multiple database schemas - one for each customer. My strategy for indexing with elasticsearch for now is to use the same index across customers, providing an additional property with the customer id/slug, and then making an alias for the index that has the customer filter already applied, so I can just query with that.

This also means that in order to make the initial indexing, I need to run the `scout:import` command multiple times - once for each customer. So I want to loop over the database connections and import the data. However, the `ImportCommand` deletes the indexes before it imports. So on each new call for each customer, the previous customer's data would be overwritten and so on.

I don't want to write all this from scratch because you've done so much great work here! So I might do something dirty and use some of your internal classes to make what I want, locking my composer version to a commit :D 

I did try to make my own `Import` class which uses less of the `ImportStages` for subsequent customers, but I somehow ended up only with having the data of the first and second customers indexed, and not all the rest. So I have to look a bit more into it to see what's happening.

In any case, back to my original issue - yes, I called your command from my own custom command, which meant I have to change the signature. So that's why it would've been nice if I extended your command, appended something to the signature, and had access to your command as a parent.

But I don't think that will even help in my case, because I need different functionality in the `Import` all together. So feel free to close this.

I also welcome any tips you might have on achieving what I described above 😃

**Comment by matchish** [comment]
Take a look in https://github.com/matchish/laravel-scout-elasticsearch/blob/f65731880ac8c2c42c6790e8917550cdca8e30ab/src/Searchable/DefaultImportSource.php#L49

You can combine your models with different connections there, and chunk all your models. Then it will be imported in the same index.

**Comment by matchish** [comment]
Here is example how to inject your `ImportSource`
https://github.com/matchish/laravel-scout-elasticsearch/tree/f65731880ac8c2c42c6790e8917550cdca8e30ab#eager-load

**Comment by denitsa-cm** [comment]
@matchish Oh, that might actually work! I'm gonna try to switch the connections in there. Don't know why I didn't think about it - thank you.

As for why I wasn't seeing some of my data - figured I need a custom scout key because of collisions across schema, so I'm adding me some uuid columns.

Thanks again!
