### ISSUE TITLE
 Elasticsearch\Common\Exceptions\NoNodesAvailableException | No alive nodes found in your cluster

### ISSUE THREAD

**Issue by denymack** [matchish/laravel-scout-elasticsearch#116]
Hello there. I'm new to Elasticsearch. I want to use it in my project. First of all thank you for making this package. I did not understand how the building should be applied. The document was very difficult for me to understand. Do you have the opportunity to publish a sample application or a simpler narration?

I also encountered an error.

**php artisan scout:import**

```
scout::import.start

   Elasticsearch\Common\Exceptions\NoNodesAvailableException 

  No alive nodes found in your cluster

  at vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:50
    46|                 return $connection;
    47|             }
    48|         }
    49| 
  > 50|         throw new NoNodesAvailableException("No alive nodes found in your cluster");
    51|     }
    52| 
    53|     public function scheduleCheck(): void
    54|     {

      +55 vendor frames
  56  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Model** 

```
class User extends Authenticatable
{
  use Notifiable, Searchable;
  
  public function searchableAs()
  {
    return 'users';
  }
  
  public function toSearchableArray()
  {
    $array = $this->toArray();
    
    // Customize array...
    
    return $array;
  }
}
```

**.env**

```
SCOUT_DRIVER=Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine
ELASTICSEARCH_HOST=localhost:9200
```

I think he says that I could not contact Elasticsearch. But when I redirected to localhost: 9200, the

 ```
output looks like this:
{
"name": "node",
"cluster_name": "cluster",
"cluster_uuid": "RKjSSOsawA6x04QHroEz2w",
"version": {
"number": "7.6.2",
"build_flavor": "default",
"build_type": "docker",
"build_hash": "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
"build_date": "2020-03-26T06:34:37.794943Z",
"build_snapshot": false,
"lucene_version": "8.4.0",
"minimum_wire_compatibility_version": "6.8.0",
"minimum_index_compatibility_version": "6.0.0-beta1"
},
"tagline": "You Know, for Search"
}
```

**Comment by martin-ostlund** [comment]
Hello,

This looks like an issue in your Elasticsearch setup. "No alive nodes found in your cluster". 
You've specified ELASTICSEARCH_HOST to localhost port 9200. Make sure this is correct.

**Comment by denymack** [comment]
@martin-ostlund 
composer.json:
```
"elasticsearch/elasticsearch": "^7.6"
```

The error continues when you perform 'composer update'.

**Comment by martin-ostlund** [comment]
Test with curl localhost:9200/

**Comment by matchish** [comment]
https://stackoverflow.com/questions/56825683/why-am-i-getting-no-alive-nodes-found-in-your-cluster-using-laravel-and-docker/56847295#56847295

**Comment by matchish** [comment]
> Hello there. I'm new to Elasticsearch. I want to use it in my project. First of all thank you for making this package. I did not understand how the building should be applied. The document was very difficult for me to understand. Do you have the opportunity to publish a sample application or a simpler narration?
> 
> I also encountered an error.
> 
> **php artisan scout:import**
> 
> ```
> scout::import.start
> 
>    Elasticsearch\Common\Exceptions\NoNodesAvailableException 
> 
>   No alive nodes found in your cluster
> 
>   at vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:50
>     46|                 return $connection;
>     47|             }
>     48|         }
>     49| 
>   > 50|         throw new NoNodesAvailableException("No alive nodes found in your cluster");
>     51|     }
>     52| 
>     53|     public function scheduleCheck(): void
>     54|     {
> 
>       +55 vendor frames
>   56  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle()
> ```
> 
> **Model**
> 
> ```
> class User extends Authenticatable
> {
>   use Notifiable, Searchable;
>   
>   public function searchableAs()
>   {
>     return 'users';
>   }
>   
>   public function toSearchableArray()
>   {
>     $array = $this->toArray();
>     
>     // Customize array...
>     
>     return $array;
>   }
> }
> ```
> 
> **.env**
> 
> ```
> SCOUT_DRIVER=Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine
> ELASTICSEARCH_HOST=localhost:9200
> ```
> 
> I think he says that I could not contact Elasticsearch. But when I redirected to localhost: 9200, the
> 
> ```
> output looks like this:
> {
> "name": "node",
> "cluster_name": "cluster",
> "cluster_uuid": "RKjSSOsawA6x04QHroEz2w",
> "version": {
> "number": "7.6.2",
> "build_flavor": "default",
> "build_type": "docker",
> "build_hash": "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
> "build_date": "2020-03-26T06:34:37.794943Z",
> "build_snapshot": false,
> "lucene_version": "8.4.0",
> "minimum_wire_compatibility_version": "6.8.0",
> "minimum_index_compatibility_version": "6.0.0-beta1"
> },
> "tagline": "You Know, for Search"
> }
> ```

Hello! Thanks for idea and nice words) Feel free to open feature request for demo application. Maybe someone from community implement it

**Comment by denymack** [comment]
@matchish 
Thank you 👍 
Since I am new to Elasticsearch, I had trouble understanding the document. Is there a sample project that includes basic operations?

**Comment by matchish** [comment]
Here https://github.com/matchish/scout-import-benchmark some old repo.

**Comment by denymack** [comment]
Thank you very much 😄
