### ISSUE TITLE
[BUG] Scout soft deletes requires all models to support softdeletes trait.

### ISSUE THREAD

**Issue by mattallenuk** [matchish/laravel-scout-elasticsearch#117]
**Describe the bug**
If Scout is configured to do soft deletes then currently all models are required to support soft deletes as DefaultImportSource::newQuery() doesn't check for existence of withTrashed() when soft deletes are turned on. Is it possible to have the code updated so that soft deletes on a model are optional when soft deletes are turned on in Scout.

**To Reproduce**
1. Create a model with softdelete trait and searchable trait.
2. Create a model with a searchable trait but no softdelete trait.
2. Set config.scout.soft_delete to true
3. Run php artisan scout:import

**Expected behavior**
I would expect the import to work with no errors.

I have for the time being created a custom ImportSourceFactory that uses a custom copy of DefaultImportSource, but this is likely to be a temporary solution and there may be other instances in the code where withTrashed() is assumed to exist.

**Comment by matchish** [comment]
What version do you use?
There is a fix in `3.0.1` https://github.com/matchish/laravel-scout-elasticsearch/pull/89
Don't it fix the issue?

**Comment by mattallenuk** [comment]
Apologies I didn't see that PR, should have checked those. The managed cloud service I am using only supports ES 6, so I'm having to use 2.1 for the moment :( But I will see if I can incorporate that change from the PR). Thanks for getting back to me.

**Comment by matchish** [comment]
No worries) Feel free to send a PR to a `2.x` branch if you fix the issue using changes from the PR.

**Comment by mattallenuk** [comment]
Thank you I will do that.
