### ISSUE TITLE
Prevent Duplicate Hits

### ISSUE THREAD

**Issue by mlantz** [matchish/laravel-scout-elasticsearch#120]
I have a project where we use this scout engine. It takes about 4 hours to reindex the data. I discovered that due to the alias setup for the indices I had to specify one of the indexes to prevent the duplicates from showing up. 

```    
$params = \Matchish\ScoutElasticSearch\ElasticSearch\Params\Indices\Alias\Get::anyIndex($model->searchableAs());
$indices = $client->indices()->getAliases($params->toArray());

$indexKeys = array_keys($indices);

return $client->search([
    'index' => $indexKeys[0],
    'body' => $body->toArray()
]);
```
This is placed inside the callback method for the search as described in the readme

This does mean that for a period of time you end up with fewer results, but it appeared to be a simple way to resolve the duplicates. I'm open to any suggestion if there is a better way. If there isn't then hopefully this help someone.

**Comment by matchish** [comment]
Do you mean you have two indices during an index process (old and new)? That shouldn't be a problem. A new index is write only until indexing isn't finished

**Comment by mlantz** [comment]
Thats what I thought, is write_only a 7 feature? I'm on 6.8 still. I also realized it was much smarter to do incremental updates vs a full rebuild of the cache.

**Comment by matchish** [comment]
It's an old feature https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-aliases.html#aliases-write-index

**Comment by matchish** [comment]
Feel free to reopen the issue if you have more info
