### ISSUE TITLE
how to add _score to elements of colection or filter?

### ISSUE THREAD

**Issue by Hirokku** [matchish/laravel-scout-elasticsearch#123]
Hello. I do have this query:

`$products = Product::search($request->get('query'))
    ->where('project_id', $project->id)
    ->paginate(20);`

and looks like its working ok, but I would like to have the _score value and if possible the max_score to filter with this, something like this:

`->where('_score', '>=', 50)`

this mean, I would like to get, all records with at least 50 of 100 in score.

thanks, any help will be appreciated

**Comment by matchish** [comment]
You can construct a query you need in a callback
https://github.com/matchish/laravel-scout-elasticsearch#search
