### ISSUE TITLE
Limit total results

### ISSUE THREAD

**Issue by reinierkors** [matchish/laravel-scout-elasticsearch#124]
Hello, great package, however when paginating more than 10k results it crashes with error:
```
Result window is too large, from + size must be less than or equal to: [10000] but was [10008]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
```

Right now I'm using:
```php
Post::search($query)->paginate(18);
```

and because I don't want to hurt my processor more or use more RAM, I want to limit the amount of results returned.

What would be the best way to achieve this? Thanks

**Comment by matchish** [comment]
Hello! Thanks for your kind words) Do you have the issue on the first page? Did you try to construct a query using scroll api?

**Comment by reinierkors** [comment]
I've noticed the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-scroll.html) says: "Scrolling is not intended for real time user requests, but rather for processing large amounts of data, e.g. in order to reindex the contents of one index into a new index with a different configuration."

So I was hesitant on using it, but might give it a shot anyways.

**Comment by dragonfire1119** [comment]
The only way I have figured out how to get passed with error is narrowing down the results below 10k. The Laravel Pagination doesn't help with this issue.

**Comment by dragonfire1119** [comment]
The only way I have figured out how to get passed this error is by narrowing down the results below 10k. The Laravel Pagination doesn't help with this issue.

**Comment by matchish** [comment]
> I've noticed the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-scroll.html) says: "Scrolling is not intended for real time user requests, but rather for processing large amounts of data, e.g. in order to reindex the contents of one index into a new index with a different configuration."
> 
> So I was hesitant on using it, but might give it a shot anyways.

I believe they said it because usually real users need only few first pages. As I remember google search also restrict search results

**Comment by reinierkors** [comment]
I fixed it by using a custom LengthAwarePaginator:

```php
$query = $request->input('query');
$perPage = 20;
$maxPages = 100;
$maxResults = $maxPages * $perPage;
$currentPage = LengthAwarePaginator::resolveCurrentPage();

$results = Post::search($query)->paginate($perPage);
$results = new LengthAwarePaginator(
    $results->getCollection(),
    $results->total() < $maxResults ? $results->total() : $maxResults,
    $perPage,
    $currentPage,
    [
        'path' => $request->url(),
        'query' => [
            'query' => $query,
            'page' => $currentPage
        ]
    ]
);

if ($currentPage > $results->lastPage()) {
    abort(404);
}
```
