### ISSUE TITLE
[Feature] Upgrade to Laravel 8

### ISSUE THREAD

**Issue by sachin-acto** [matchish/laravel-scout-elasticsearch#128]
Thank you for great package 👍 

Just want to know the plan to support Laravel 8. 
We trying to update our codebase, but unable to since this package doesn't support Laravel 8 yet.

**Comment by matchish** [comment]
Thanks for your kind words) Feel free to contribute. I don't think there is breaking changes

**Comment by sachin-acto** [comment]
@matchish thanks. I have opened up a PR from a different account of mine. Please do have a look

**Comment by matchish** [comment]
Done
