### ISSUE TITLE
[BUG] Compatible with Laravel Telescope in Composer require-dev

### ISSUE THREAD

**Issue by ametad** [matchish/laravel-scout-elasticsearch#135]
**Describe the bug**
`php artisan scout:import` crashes when Laravel Telescope is configured as "dev" requirement, to only load in "local" environment.

**To Reproduce**
1. Require Laravel Telescope as dev req.: `composer require laravel/telescope --dev`
1. Install Telescope as described here https://laravel.com/docs/telescope#installation, for dev!
    1. `php artisan telescope:install` and `php artisan migrate`.
    1. After running telescope:install, you should remove the TelescopeServiceProvider service provider registration from your app configuration file. Instead, manually register the service provider in the register method of your AppServiceProvider.
1. Try `php artisan scout:import` (without extra argument). This throws exception: "Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found"

**Expected behavior**
Running `scout:import` should only try to load classes with `require_once $file;` that are Eloquent model and Searchable only. If possible.

**Additional context**

I think the problem is located here:
https://github.com/matchish/laravel-scout-elasticsearch/blob/06c90914668942b23ffaff7d58af5b9db1901fb1/src/Searchable/SearchableListFactory.php#L69

There ALL php files in the `app` directory are loaded, even when it is not used at runtime.

In my setup the class `\App\Providers\TelescopeServiceProvider` should only be loaded in dev, but is now loaded anyway by `\Matchish\ScoutElasticSearch\Searchable\SearchableListFactory::getProjectClasses`. 

The intention of my setup is made clear in `\App\Providers\AppServiceProvider::register`:

```php
        if ($this->app->isLocal()) {
            $this->app->register(TelescopeServiceProvider::class);
        }
```

**Version**
Versions of Laravel, Scout, and the package.
Laravel 5.8
Scout: 7.2.1
Package: 3.0.3

**Comment by matchish** [comment]
The same issue https://github.com/algolia/scout-extended/issues/213

**Comment by matchish** [comment]
@ametad I sugest to open stackoverflow question. Maybe we can find a solution there. Post the link here to the question if you will do it pls.

**Comment by ametad** [comment]
Stackoverflow is an idea indeed 👍

**Comment by ametad** [comment]
I have another idea, a whole different approach:

What about a **config setting** that defines what searchable classes there are in your system? I think this solves it all and is the most robust implementation. Also very sufficient regarding resources and very controllable.

IMO the only reason for the short command (`artisan scout:import`) to be there in the first place is: convenience. You don't have to explicitly write all the class names you want to import. With the config in place, convenience is still very high! You only have to keep up the config with your searchable classes. I prefer this explicit way of coding anyway, because implicit ways are in the long run more difficult to maintain and understood imo.

**Comment by ametad** [comment]
We are not alone :wink: 

https://github.com/algolia/scout-extended/issues/213

**Comment by ametad** [comment]
> What about a config setting that defines what searchable classes there are in your system? I think this solves it all and is the most robust implementation. Also very sufficient regarding resources and very controllable.

What do think about this @matchish ? Perhaps with fall back to the old approach?

**Comment by matchish** [comment]
We have `searchable` argument in import console command. So we can specify what classes to import.
https://github.com/matchish/laravel-scout-elasticsearch/blob/master/src/Console/Commands/ImportCommand.php#L20

You can create a config in your application and use it with import command. You can create a new command and call import command from code with `searchable` argument loaded from the config

**Comment by ametad** [comment]
Yes of course... So your solution would be "do it yourself". No offense, you are entitled to say so. And I know that is a good solution to be usable and flexible for the majority. 

My question is: what is your philosophy about finding all the searchable models? 

In my opinion it can work in ALL scenarios when this is configurable. The other option is that there is a solution implemented for every new scenario where it was not working. This could be something that goes on and on.

BTW I do think I can come up with a solution to find searchable models when this is declared in a higher order trait.

**Comment by matchish** [comment]
For me config for searchable classes is workaround
I think we need only two options
Specify searchable models manually
Find all models with searchable trait
Until we don't have bulletproof search we can live with a solution that fit most cases.

**Comment by arturslogins** [comment]
Why this fix is not merged in latest version?

**Comment by matchish** [comment]
As I remember we had some dependencies incompatibility in php8. So I rolled back this fix until it will be fixed.

**Comment by matchish** [comment]
DO you think it should work now?
