### ISSUE TITLE
need php 8 support

### ISSUE THREAD

**Issue by simonproud** [matchish/laravel-scout-elasticsearch#137]

**Comment by matchish** [comment]
Waiting for php8 support in
https://github.com/ongr-io/ElasticsearchDSL

**Comment by ametad** [comment]
And this pack also need to support it, they are working on it:

- https://github.com/Roave/BetterReflection/issues/701

**Comment by matchish** [comment]
There is a fork of https://github.com/ongr-io/ElasticsearchDSL with php8 support https://github.com/handcraftedinthealps/ElasticsearchDSL 
We can try to use it until no php8 support in original package. 
And probably we need to rollback it https://github.com/matchish/laravel-scout-elasticsearch/pull/138 until no php8 support in https://github.com/Roave/BetterReflection/issues/701
PR are wellcome

**Comment by ametad** [comment]
Hi @matchish ,

For me it would not be a problem if `php artisan scout:import` (without additional arguments) wouldn't work. In my code I now always be explicit in what to import. So the magic of finding all searchable classes is not needed by me. Therefore, the roll back would be no problem for me.

**Comment by matchish** [comment]
Hi @ametad. Then could you rcreate `ametad/php8` branch and revert your code there. Until no php8 support in Roave/BetterReflection
Then we can try `handcraftedinthealps/ElasticsearchDSL` there with php8

**Comment by matchish** [comment]
Looks like it works https://github.com/matchish/laravel-scout-elasticsearch/tree/php8-test
Feedback are wellcome
