### ISSUE TITLE
timestamp in suffix of indexname

### ISSUE THREAD

**Issue by anton-reviakin** [matchish/laravel-scout-elasticsearch#140]
**Describe the bug**

**To Reproduce**
1. Create a model with 'Products'
2. Run a command 'artisan scout:import App\Models\Product'
3. Search term in Kibana 'GET _cat/indices'
4. See timestamp in suffix of indexname (products_1607192739)

**Version**
Laravel 8.0
Scout 8.4.0
This package (matchish/laravel-scout-elasticsearch) 4.0.3

**Comment by matchish** [comment]
I believe you've forgot to describe the bug)

**Comment by matchish** [comment]
We need timestamp for zero downtime update. Alias of the index is `products` so when you make query to `products` actually you do do it against index with timestamp

**Comment by anton-reviakin** [comment]
> We need timestamp for zero downtime update. Alias of the index is `products` so when you make query to `products` actually you do do it against index with timestamp

I understand, thanks :+1:
