### ISSUE TITLE
[Feature] Add where constraints

### ISSUE THREAD

**Issue by francoism90** [matchish/laravel-scout-elasticsearch#145]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/laravel/scout/pull/141

**Describe the solution you'd like**
I would like to use something like this:
`Books::search('..')->withIn('id, [..])` or other `where` constraints as seen in the PR.

**Describe alternatives you've considered**
Adding a marco myself, but I haven't figured out how this should be done.

**Additional context**
https://github.com/laravel/scout/issues/145#issuecomment-326502768

It seems other scout packages added these methods using marco's as well.

Thanks!

**Comment by francoism90** [comment]
Fixed by using `IdsQuery`:
```
->search('*', function ($client, $body) use ($query, $modelIds) {
                $idsQuery = new IdsQuery($modelIds);

                $body->addQuery($idsQuery);

                return $client->search([
                    'index' => $query->getModel()->searchableAs(),
                    'body' => $body->toArray(),
                ]);
            })
```

**Comment by matchish** [comment]
https://github.com/matchish/laravel-scout-elasticsearch/issues/47
