### ISSUE TITLE
[BUG] Unterminated comment starting line 23

### ISSUE THREAD

**Issue by adrianpaiva1** [matchish/laravel-scout-elasticsearch#146]
**Describe the bug**
happens when running php artisan scout:import

I currently have all of my models using my own Searchable Trait, which uses the offical scout Searchable Trait

only happens on v4.0.3

**To Reproduce**

Not if this is happening because of my custom trait, but add your own Searchable Trait
run php artisan scout:import

**Version**
4.0.3

![image](https://user-images.githubusercontent.com/19557611/102674894-868fb780-4165-11eb-8573-830fc6af260a.png)

![image](https://user-images.githubusercontent.com/19557611/102674868-75df4180-4165-11eb-89a3-f39a0b0d73f7.png)

**Comment by matchish** [comment]
Hey) Did you try 4.0.4?

**Comment by adrianpaiva1** [comment]
Unable to use 4.0.4 because of the other issue I posted. But this error is gone in 4.0.4

https://github.com/matchish/laravel-scout-elasticsearch/issues/147

**Comment by matchish** [comment]
Probably we'll rollback to 4.0.2
So please use it for now
https://github.com/matchish/laravel-scout-elasticsearch/issues/139#issuecomment-743732711

**Comment by ametad** [comment]
Fixed in 4.0.5

https://github.com/matchish/laravel-scout-elasticsearch/pull/152

**Comment by matchish** [comment]
@adrianpaiva1 Feel free to reopen if you still have the issue after update to `4.0.5`
