### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by north521** [matchish/laravel-scout-elasticsearch#148]
$list =  AppModel::search('',
            function ($client, $body){
                $body = new Search();
                $body->addQuery(new MatchQuery('company.keyword','Spil Games'));
                return $client->search(['index' => 'ly-apps', 'body' => $body->toArray()]);
            })->paginate();
        return $list;

分页不起作用

**Comment by matchish** [comment]
Could you add a fail test with the issue?

**Comment by north521** [comment]
> 您可以为此问题添加失败测试吗？

传入page参数，无论请求第几页，总是返回第一页的数据

**Comment by matchish** [comment]
Pls write in english
