### ISSUE TITLE
[Question] how to include custom attributes in Eloquent model of search results

### ISSUE THREAD

**Issue by FreekU** [matchish/laravel-scout-elasticsearch#149]
Does anyone know how to include custom attributes from the index into the model when returning search results?

I've added custom fields in the index using `toSearchableArray` and these are showing up when returning the raw results. However, when I use the `->get()`, the custom fields are not included in the model objects (as they are not in the underlying database table), and I can't seem to find out how to include them.

**Comment by ametad** [comment]
Two options:

### Eloquent accessor

**Comment by ametad** [comment]
PS. You can implement your own class by binding it in the ioc. This can be done in `AppServiceProvider::register()`:

```php
        $this->app->bind(
            'Matchish\ScoutElasticSearch\ElasticSearch\HitsIteratorAggregate',
            'App\Elasticsearch\EloquentHitsIteratorAggregate'
        );
```

**Comment by FreekU** [comment]
Great, thanks for the extensive reply @ametad! I've been able to add the required fields, thanks!
