### ISSUE TITLE
[Question] How to include custom attributes in search results?

### ISSUE THREAD

**Issue by FreekU** [matchish/laravel-scout-elasticsearch#150]
Does anyone know how to include custom attributes from the index into the model when returning search results?

I've added custom fields in the index using `toSearchableArray` and these are showing up when returning the raw results. However, when I use the `->get()`, the custom fields are not included in the model objects (as they are not in the underlying database table), and I can't seem to find out how to include them.

**Comment by matchish** [comment]
https://github.com/matchish/laravel-scout-elasticsearch#working-with-results

**Comment by FreekU** [comment]
Thanks for the hint, Sergey! 

For future reference for others looking into this, I've followed the approach outlined here https://github.com/matchish/laravel-scout-elasticsearch/issues/28#issuecomment-583736966 and added an additional function that's called in the `getIterator()` function:

```
private function mergeCustomFieldsIntoModels($eloquentHits, $raw){     
        return collect($eloquentHits)->map(function(Model $eloquentHit) use($raw){

            $raw = collect($raw)
                ->where('_source.__class_name', get_class($eloquentHit))
                ->where('_source.id', $eloquentHit->id)
                ->first()['_source'];
            
            $source = collect($raw);
            $eloquentHit->setAttribute('published_from', $source->get('published_from'));
            $eloquentHit->setAttribute('published_to', $source->get('published_to'));

            return $eloquentHit;
        })->all();
    }
```
