### ISSUE TITLE
[BUG] Commands no longer overwrite default Laravel Scout commands

### ISSUE THREAD

**Issue by serpentblade** [matchish/laravel-scout-elasticsearch#160]
**Describe the bug**
A recent change in Laravel Scout v8.6.1 moved commands to be registered during boot():
https://github.com/laravel/scout/pull/453

This causes the default scout:import to be used rather than this service, regardless of the order of ServiceProviders.

**To Reproduce**
1. Upgrade to Laravel Scout v8.6.1
2. Run command `php artisan scout:import 'App\YourModel'`
3. Artisan will run the default import command instead of this package's command

**Expected behavior**
This service should override the scout:import command

**Additional context**
I believe a simple fix should be move to move the call to `registerCommands()` inside of `boot()` instead of `register()`, however I don't know what the impact would be to versions of Scout prior to v8.6.1.  My guess is it would be okay as `boot()` always occurs after `register()` so it would still properly override. Some testing against different versions of v8 may be required or upping the minimum version dependency to laravel\scout ^8.6.1.

**Version**
Versions of Laravel, Scout, and the package.

**Comment by matchish** [comment]
>My guess is it would be okay as boot() always occurs after register() so it would still properly override.
Agree
