### ISSUE TITLE
there not supported securety

### ISSUE THREAD

**Issue by uyson** [matchish/laravel-scout-elasticsearch#163]
config not supported eclasticsearch authentication

**Comment by uyson** [comment]
Is  there have any way to fix my problem? and I trying to fix hardcoding in ElasticSearchServiceProvider `ClientBuilder::create()
                    ->setHosts([config('elasticsearch.host')])
                    ->setBasicAuthentication(config('elasticsearch.user'), config('elasticsearch.password'))->build();`

**Comment by matchish** [comment]
https://github.com/matchish/laravel-scout-elasticsearch#rocket-installation
Implementing and publishing your own `ElasticSearchServiceProvider` should help
That's where you config elasticsearch client. We are using https://github.com/elastic/elasticsearch-php .nothing specific to scout
