### ISSUE TITLE
[BUG] high memory usage

### ISSUE THREAD

**Issue by uyson** [matchish/laravel-scout-elasticsearch#164]
**Describe the bug**
there has memory error

**To Reproduce**
import 12m record from mysql

**Expected behavior**
import all data to es

**Additional context**
error message:
Importing [App\Models\User\VideoPlayHistory]
Indexing...
 4674/24202 [⚬⚬⚬⚬⚬➤⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬]  19%
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 118784 bytes) in /web/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 317
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 65536 bytes) in /web/vendor/jakub-onderka/php-console-highlighter/src/Highlighter.php on line 8

**Version**
Versions of Laravel, Scout, and the package.
laravel: 6.20.13
scout: 8.6.0
laravel-scout-elasticsearch: 4.0.5

**Comment by matchish** [comment]
Could you check how much it will index if you increase chunk size to `1000`?

**Comment by uyson** [comment]
> Could you check how much it will index if you increase chunk size to `1000`?

default chunk size

**Comment by matchish** [comment]
Default chunk size is `500` could you increase to `1000` and try import again. I'm curious how much chunks will be imported then

**Comment by uyson** [comment]
mybe there has information that you want to know 
4674/24202 [⚬⚬⚬⚬⚬➤⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬⚬] 19%

**Comment by matchish** [comment]
This is for chunk 500 I'm interesting how it change with chunk 1000

**Comment by uyson** [comment]
I have changed chank size to 1000, and memory usage keeps going up every chunk is impoted.

**Comment by uyson** [comment]
I am so sorry, I cause the problem, load the some other relation in the toSearchableArray , so memory is keeps going up.
example:
```
public function toSearchableArray()
    {

        $array = $this->toArray();
        $array['created_at']        = $this->created_at->timestamp;
        $array['updated_at']        = $this->updated_at->timestamp;

        $array['nick_name'] = $this->user->nick_name;

        return $array;
```

**Comment by uyson** [comment]
I am so confusing, why the memory is keeps going up?

**Comment by matchish** [comment]
Have you found why the memory is keeps going up?

**Comment by matchish** [comment]
Have you tried this https://github.com/matchish/laravel-scout-elasticsearch#eager-load ?

**Comment by uyson** [comment]
I haven't found out where the problem is， some releation I can't use eager load. I trying to update mysql structure and use eager load.

**Comment by uyson** [comment]
But I'm sure we can't get any relation data  in ToSearchArray.  It will cause memory usage to increase constantly

**Comment by uyson** [comment]
> In case anyone stumbles upon this, I managed to work around it by running `php artisan tinker` and there running
> 
> ```
> ini_set('memory_limit', '3G');
> Artisan::call('scout:import "<model>"');
> ```
is there enable debug option

**Comment by AngeloKarugo** [comment]
> In case anyone stumbles upon this, I managed to work around it by running `php artisan tinker` and there running
> 
> ```
> ini_set('memory_limit', '3G');
> Artisan::call('scout:import "<model>"');
> ```

Building on @mvrska's answer above, if you run `scout:import` using a scheduled task you can create a custom command that sets memory limit then executes `scout:import` command. Something like:

```
# app/Console/Commands/CustomIndexingCommand.php
...
class CustomIndexingCommand extends Command {
    protected $signature = 'app:custom-search-index';

    public function handle() {
        ini_set('memory_limit', '3G');
        Artisan::call('scout:import');
    }
}
```

```
# app/Console/Kernel.php
...
// $schedule->command('scout:reimport');
$schedule->command('app:custom-search-index');
...
```

**Comment by uyson** [comment]
My issue was caused by writing a large amount of logs, which led to high memory usage. After disabling the logging, the memory usage was significantly reduced.
