### ISSUE TITLE
Laravel scout 9 support

### ISSUE THREAD

**Issue by parsagholipour** [matchish/laravel-scout-elasticsearch#165]
I'm facing this issue using the package for scout v9
```
 matchish/laravel-scout-elasticsearch dev-php8 requires laravel/scout ^8.0 ->
 found laravel/scout[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0)
```

**Comment by matchish** [comment]
https://github.com/matchish/laravel-scout-elasticsearch/issues/160
There is small braking changes in scout `8.6.1` the fix might simple but someone have to implement it and be sure that tests not broken. Fill free to send the PR

**Comment by matchish** [comment]
There is dev branch with scout 9 support https://github.com/matchish/laravel-scout-elasticsearch/tree/php8-test
Feedback are welcome

**Comment by madalinignisca** [comment]
Are you going to support only PHP 8 with 5.x? Scout 9 supports minimal php 7.3, and this package bumping to 8.0 would not allow projects that use Elastic PHP APM for monitoring to update to it (there is no php 8.0 support for monitoring - I know it has nothing to do with the project, but monitoring php 8.0 is not realistic in the enterprise world yet).

**Comment by matchish** [comment]
What is your case to use scout 9 over 8?

**Comment by madalinignisca** [comment]
Sorry, I don't understand your question, but as long as Scout 9.x is >=7.3, including 8.0, what is your reason to enforce people on php 8.0 that has poor monitoring support at this moment? If Scout 9.x will support, why don't you inline the package with it?

**Comment by matchish** [comment]
If you don't need php8 you can use 4x version. I don't see pros in scout 9. Main reason of 5x is support php8
Yes we can add support php7.3 to 5x but I don't have time for it now. So pr welcome. But be sure that tests are passes. And php7.3 added to travis config matrix for ci
Also scout 9 support can be added to 4x version as described in previous comment

**Comment by matchish** [comment]
Support in `4.0.7`
