### ISSUE TITLE
[BUG] ElasticSearchServiceProvider is not registered in composer.json for autodiscovery.

### ISSUE THREAD

**Issue by ghostzero** [matchish/laravel-scout-elasticsearch#171]
**Describe the bug**

I figured out, that we need manually add ElasticSearchServiceProvider in the app.php config to be able to use this package.

**To Reproduce**
1. Install package
2. Load package via auto discovery
3. use search function.

**Expected behavior**

Both service provider are loaded.

**Version**
dev-php8

**Comment by matchish** [comment]
Often we need to configure elasticsearch by ourself
https://github.com/matchish/laravel-scout-elasticsearch/issues/110
That's why we don't use autodiscovery
This moment covered in README https://github.com/matchish/laravel-scout-elasticsearch#rocket-installation
