### ISSUE TITLE
eager load is not working

### ISSUE THREAD

**Issue by Orest-Divintari** [matchish/laravel-scout-elasticsearch#176]
> Software Version
> PHP 7.2.5
> Elasticsearch	7.9.3
> Laravel	7
> Laravel Scout 8.3	

I followed the steps from the eager load section but the method `from` in the `MyImportSourceFactory` is not triggered

Should we call that method manually ? Or it is supposed to be triggered automatically ? 

Also I saw that now there is a method named `makeAllSearchableUsing` in the `Searchable` class which can be used to eager load relationships. Is that supported from the package ?

**Comment by matchish** [comment]
Have you registered `MyImportSourceFactory` in a service  provider?

**Comment by matchish** [comment]
`makeAllSearchableUsing` is working if you run `makeAllSearchable` but in the package command it ignored for now. Probably it make sense to use it in `DefaultImportSource`. Thanks for mentioned it. I've missed this new api

**Comment by Orest-Divintari** [comment]
I have not created a new `ServiceProvider`, I registered it in the `AppServiceProvider`

```
namespace App\Providers;

class AppServiceProvider
{
    use Matchish\ScoutElasticSearch\Searchable\ImportSourceFactory;
    ...
    public function register(): void
    {
          $this->app->bind(ImportSourceFactory::class, MyImportSourceFactory::class);
    }
}


namespace Matchish\ScoutElasticSearch\Searchable;

use Matchish\ScoutElasticSearch\Searchable\DefaultImportSource;
use Matchish\ScoutElasticSearch\Searchable\ImportSourceFactory;
use WithSearchInfoScope;

final class MyImportSourceFactory implements ImportSourceFactory
{
    public static function from(string $className): ImportSource
    {
        return new DefaultImportSource($className, [new WithSearchInfoScope()]);
    }
}
```


I also tried to see if the `DefaultImportSourceFactory`, after I commented out the line

 ` $this->app->bind(ImportSourceFactory::class, MyImportSourceFactory::class);`

But again it was not triggered. 

Am I missing something ?

```
final class DefaultImportSourceFactory implements ImportSourceFactory
{
    public static function from(string $className): ImportSource
    {
        dd('asds');
        return new DefaultImportSource($className);
    }
}
```

**Comment by Orest-Divintari** [comment]
I also found the ```ImportCommand``` class that actually instantiates and calls the ```ImportSourceFactory```

```
  private function import(string $searchable): void
    {
       dd('ssssss');
        $sourceFactory = app(ImportSourceFactory::class);
        $source = $sourceFactory::from($searchable);
     }
```
And it seems that neither this function is called.

**Comment by matchish** [comment]
What version of the package do you use? Actually everything you mentioned covered with tests so should work

**Comment by Orest-Divintari** [comment]
`"matchish/laravel-scout-elasticsearch": "^4.0"`

**Comment by Orest-Divintari** [comment]
I created a new project to check if it works.

> Software Version
> PHP 7.3
> Elasticsearch	7.9.3
> Laravel	8.4
> Laravel Scout 8.5	
> matchish/laravel-scout-elasticsearch 4.0

Unfortunately, the issue remains. The `import` method is not called

```
final class ImportCommand extends Command
{
     private function import(string $searchable): void
     {
          dd('ssssss');
          $sourceFactory = app(ImportSourceFactory::class);
          $source = $sourceFactory::from($searchable);
      }
}
```

**Comment by matchish** [comment]
Could you create a repo with docker-compose that I try?

**Comment by Orest-Divintari** [comment]
https://github.com/Orest-Divintari/laravel_test_elastic 

There is a test named `ElasticTest` which creates records and then executes a search. 

I have not added any custom `ImportSource`, you can try to `dd('something')` in `ImportCommand` to check if it is triggered

**Comment by matchish** [comment]
I've tried your app and it works
![image](https://user-images.githubusercontent.com/818563/126279428-a6885d08-d7f5-447b-85e0-af6c5b444e03.png)

**Comment by Orest-Divintari** [comment]
The search functionality works.
What doesn't work, at least for me, is the `eager loading`. 
As I mentioned earlier, initially I tried to replace the `DefaultImportSourceFactory` with `MyImportSourceFactory` and it didn't work. Then I realised that the `ImportCommant` that instantiates the `ImportSourceFactory` is not trigged. 

```
final class ImportCommand extends Command
{
     private function import(string $searchable): void
     {
          dd('ssssss');
          $sourceFactory = app(ImportSourceFactory::class);
          $source = $sourceFactory::from($searchable);
      }
}
```

**Comment by matchish** [comment]
Works as well. Here is app service provider
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Matchish\ScoutElasticSearch\Searchable\ImportSourceFactory;
use Matchish\ScoutElasticSearch\Searchable\ImportSource;
use Matchish\ScoutElasticSearch\Searchable\DefaultImportSource;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Scope;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(ImportSourceFactory::class, MyImportSourceFactory::class);
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}

final class MyImportSourceFactory implements ImportSourceFactory
{
    public static function from(string $className): ImportSource
    {
        //Add all required scopes
        return new DefaultImportSource($className, [new HelloScope()]);
    }
}

class HelloScope implements Scope {

    /**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param \Illuminate\Database\Eloquent\Builder $builder
     * @param \Illuminate\Database\Eloquent\Model $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->where('title', 'hello');
    }
}
```
![image](https://user-images.githubusercontent.com/818563/126297393-69990523-5382-427a-87ad-cc15904f2de4.png)

**Comment by Orest-Divintari** [comment]
It still doesn't work for me.

Did you do anything else besides the code that you posted above ?

**Comment by matchish** [comment]
Only created threads from tinker

> I've tried your app and it works
> ![image](https://user-images.githubusercontent.com/818563/126279428-a6885d08-d7f5-447b-85e0-af6c5b444e03.png)

**Comment by matchish** [comment]
I mean 

> The search functionality works.
> What doesn't work, at least for me, is the `eager loading`.
> As I mentioned earlier, initially I tried to replace the `DefaultImportSourceFactory` with `MyImportSourceFactory` and it didn't work. Then I noticed that the `ImportCommant` that instantiates the `ImportSourceFactory` is not trigged.
> 
> ```
> final class ImportCommand extends Command
> {
>      private function import(string $searchable): void
>      {
>           dd('ssssss');
>           $sourceFactory = app(ImportSourceFactory::class);
>           $source = $sourceFactory::from($searchable);
>       }
> }
> ```

I think I understood what is the cause of your issue. This code called only if you use scout:import command.

**Comment by matchish** [comment]
Related comment https://github.com/matchish/laravel-scout-elasticsearch/issues/111#issuecomment-607791773

By the way with new scout api ::searchableWith you can to eager load there. I didn't try yet but should work

**Comment by Orest-Divintari** [comment]
> I mean
> 
> > The search functionality works.
> > What doesn't work, at least for me, is the `eager loading`.
> > As I mentioned earlier, initially I tried to replace the `DefaultImportSourceFactory` with `MyImportSourceFactory` and it didn't work. Then I noticed that the `ImportCommant` that instantiates the `ImportSourceFactory` is not trigged.
> > ```
> > final class ImportCommand extends Command
> > {
> >      private function import(string $searchable): void
> >      {
> >           dd('ssssss');
> >           $sourceFactory = app(ImportSourceFactory::class);
> >           $source = $sourceFactory::from($searchable);
> >       }
> > }
> > ```
> 
> I think I understood what is the cause of your issue. This code called only if you use scout:import command.

```
class HelloScope implements Scope
{

    /**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param \Illuminate\Database\Eloquent\Builder $builder
     * @param \Illuminate\Database\Eloquent\Model $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        dd('hello friend');
        $builder->where('title', 'hello');
    }
```

Indeed when I ran `scout:import` the `hello friend` was printed.

But shouldn't the scope be called every time I run the test ? 

Because after I ran `scout:import` I tried to run the `ElasticTest` and the `hello friend` was not printed

**Comment by matchish** [comment]
In your test import command not called. You just created threads using the factory. It also push data to ES but without eager loading. And for some people it's important to be flexible https://github.com/matchish/laravel-scout-elasticsearch/issues/111#issuecomment-607791773

**Comment by matchish** [comment]
If you register your scopes globally it will eager load all the time

**Comment by matchish** [comment]
Sorry for typos writing from phone

**Comment by Orest-Divintari** [comment]
> In your test import command not called. You just created threads using the factory. It also push data to ES but without eager loading. And for some people it's important to be flexible [#111 (comment)](https://github.com/matchish/laravel-scout-elasticsearch/issues/111#issuecomment-607791773)

the solution you linked works.

I created a global scope and added it to `bootSearchable` 

But I think that if I update `Scout` the `Searchable` trait will be overridden by the updated one and my code will be lost.

Anyway it is a solution for now. 

Thank you

**Comment by Orest-Divintari** [comment]
> In your test import command not called. You just created threads using the factory. It also push data to ES but without eager loading. And for some people it's important to be flexible [#111 (comment)](https://github.com/matchish/laravel-scout-elasticsearch/issues/111#issuecomment-607791773)

Do you mean that every time I create a `Thread` I have to run the command `scout:import` ? 

Shouldn't that run automatically by the framework  after you run it once in the terminal ?

I also have a question about the `ImportSourceFactory`, does it store the model with the relationships in the index ? or it loads the relationships after you search for a model ?

**Comment by matchish** [comment]
Saved thread will be imported without scout:import command also

**Comment by matchish** [comment]
ImportSourceFactory used only to import data to ES. If you want to eager load relationships on search then you need https://github.com/matchish/laravel-scout-elasticsearch#working-with-results

**Comment by mauricius** [comment]
@arturslogins just stumbled upon this issue, but it's actually very easy to use Scout's native `makeAllSearchableUsing` method in this package

```php
namespace App\Providers;

use Matchish\ScoutElasticSearch\Searchable\ImportSourceFactory;

class AppServiceProvider
{
    public function register(): void
    {
        $this->app->bind(ImportSourceFactory::class, MyImportSourceFactory::class);
    }
}
```

```php
namespace App\Services\ElasticSearch;

use Matchish\ScoutElasticSearch\Searchable\DefaultImportSource;
use Matchish\ScoutElasticSearch\Searchable\ImportSource;
use Matchish\ScoutElasticSearch\Searchable\ImportSourceFactory;

final class MyImportSourceFactory implements ImportSourceFactory
{
    public static function from(string $className): ImportSource
    {
        return new DefaultImportSource($className, [new ModelSearchableQueryScope()]);
    }
}
```

```php
class ModelSearchableQueryScope implements Scope
{
    public function apply(Builder $builder, Model $model): void
    {
        if (in_array('makeAllSearchableUsing', get_class_methods($model), true)) {
            $model->makeAllSearchableUsing($builder);
        };
    }
}
```

The only thing to be aware of it that the visibility of the method must be set to `public` (unless you want to use Reflection)

```php
class MyModel extends Model
{
    public function makeAllSearchableUsing($query)
    {
        return $query->with('relationship');
    }
}
```
