### ISSUE TITLE
where filters with operators

### ISSUE THREAD

**Issue by Orest-Divintari** [matchish/laravel-scout-elasticsearch#179]
I am working on the implementation of where filters with operators,  such as 

```
where('price', '>=', 100);
whereBetween('price', [100, 200]);
```

And I was thinking of adding tests in the `SearchTest` which is in the `feature` directory. I remember that you said that you don't want a separate test method for each filter, but in this case there are quite a few filters that I want to add and it will be a mess if I add all of them in a single test method.

Is it ok if I create a separate test method for each filter ?

**Comment by matchish** [comment]
Unfortunately Laravel scout don't support whereBetween filter. And I prefer to not add methods that original package don't support. Maybe there is a point to create a repo with extra macros. Feel free to create your if you are ready to support it. I'll mention(link) it here with pleasure. Here is example of a macro https://github.com/matchish/laravel-scout-elasticsearch/issues/47 https://gist.github.com/mackhankins/454d4114e34d5c885fd66fcdf0081550

**Comment by matchish** [comment]
About tests yes if it prevent mess then of course it's ok to have different cases. But better unit tests then e2e
