### ISSUE TITLE
Search only returns 10 results

### ISSUE THREAD

**Issue by jrichmo93** [matchish/laravel-scout-elasticsearch#18]
Running the search an a model only returns 10 results. Is there any way to set the limit to return more?

**Comment by matchish** [comment]
10 is default size https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

There is two way to set new size

1. Using paginate
```
Book::search('zonga')->paginate(100);
```
2. Using search callback
```
$results = Book::search('zonga', function($client, $body) {
    $body->setSize(100);    
    return $client->search(['index' => 'books', 'body' => $body->toArray()]);
})->get();
```

**Comment by ian-patel** [comment]
@matchish How paginations works?

**Comment by matchish** [comment]
> How paginations works?

@ian-patel What do you mean?

**Comment by matchish** [comment]
> and is it possible egger loading?

https://github.com/laravel/scout/pull/92#issuecomment-252427676

Also you can pass callback to `query` method. 

```
Book::search('harry')->query(function($query) {
    return $query->with('author');
})->paginate(15);
```
