### ISSUE TITLE
ElasticSearch 8.0 support

### ISSUE THREAD

**Issue by matchish** [matchish/laravel-scout-elasticsearch#184]
Elasticsearch 8.0 released https://www.elastic.co/guide/en/elasticsearch/reference/master/release-notes-8.0.0-alpha1.html
Vote this post if you need support of it in this package

**Comment by matchish** [comment]
ElasticSearch 8 released. Waiting when `handcraftedinthealps/elasticsearch-dsl` support it

**Comment by hkulekci** [comment]
Hello everyone, I am following this library and I want to help with about 8.0 support I created a draft here https://github.com/hkulekci/ElasticsearchDSL/pull/2. I need a reviewer. Could we check together and create a PR for the `handcraftedinthealps` library?

**Comment by hkulekci** [comment]
I created a PR for the `[handcraftedinthealps/elasticsearch-dsl](https://github.com/handcraftedinthealps/ElasticsearchDSL/pull/18)` and we need to change the PHP support of the repository itself. As I see we have a PR for PHP8 here https://github.com/matchish/laravel-scout-elasticsearch/pull/188/files but it is not updated last 2 months. Do we have a plan for that PR? I think the library needs to support PHP `^7.4|^8.0`. I can look at that PR also in my free time.

**Comment by matchish** [comment]
I have closed the pr.
The package have php8 branch with php8. But I believe we need to get rid off it. 
So feel free to add php8 support to master branch.

**Comment by matchish** [comment]
I have feeling that ci doesn't work anymore so we need to migrate to GitHub actions as well. Thanks for your contribution) You have done great job!

**Comment by hkulekci** [comment]
Hey @matchish I see in your profile today that you are living in Ukraine. I am so sorry for the situation of your country. I don't know how I can explain my feelings but I hope, you are good and best wishes for the Ukraine.

**Comment by matchish** [comment]
@hkulekci Thanks for your kind words and support!! You can't imagine how big support I feel these days from your country and the whole world!! Çok teşekkür ederim, abi!!

**Comment by hkulekci** [comment]
Recent news is I had created a [PR ](https://github.com/handcraftedinthealps/ElasticsearchDSL/pull/18) and Elasticsearch published [an alpha release](https://github.com/elastic/elasticsearch-php/releases/tag/v8.0.0-alpha) for the base repository. The `handcraftedinthealps/ElasticsearchDSL` library works correctly with `8.x-dev`. So, I will try to continue with `8.x-dev`. Maybe, we can put a new release for a more recent version. You can check my latest comments on the PR.

**Comment by hkulekci** [comment]
So, the [PR on the ElasticsearchDSL](https://github.com/handcraftedinthealps/ElasticsearchDSL/pull/18) is merged. I will check the updates and try to use `8.0.0-rc1` version to test on this library.

**Comment by matchish** [comment]
Already in mastes. Kudos to @hkulekci !!!
