### ISSUE TITLE
[Feature] Can you help me about config file?

### ISSUE THREAD

**Issue by LordVersA** [matchish/laravel-scout-elasticsearch#185]
**Describe the solution you'd like**
I want a clear document for config file, and how can I customize configuration for indexing, settings and etc.

**Comment by matchish** [comment]
It's not the package specific. You have to learn elasticsearch if you want to know how to config it
If you know what you need just put it to config file.
Here is an example https://github.com/matchish/laravel-scout-elasticsearch/blob/php8/config/elasticsearch.php

**Comment by LordVersA** [comment]
I want two separated project use one dedicated server for search engine and now I don't know what should I do?
how can I install 2 elastic search in one server?

**Comment by LordVersA** [comment]
or should I use prefix for separating 2 project?

**Comment by matchish** [comment]
https://github.com/laravel/scout/blob/0137c70efb164eeeb8115a9ebb1517263b6a64ac/config/scout.php#L31

**Comment by LordVersA** [comment]
I used it but my scout search between all indexes 
my search query is:

```php
$result = Mixed::search('',function ($client,$body) use ($q){
				return $client->search([
									
									'body' => [
										
										"query" => [
											
											"query_string" => [
												
												"query" => $q ,
												"fields" => [
													"title_fa" ,
													"title_en" ,
												] ,
												"fuzziness" => "AUTO" ,
											] ,
										] ,
									],
									//"_source" => [
									//	"id" ,
									//] ,
									"from" =>0,
									"size" => 100 ,
								]);
			}
			)->within(implode(',', [
				(new Series())->searchableAs(),
				(new Movie())->searchableAs(),
			]))->raw();
```

**Comment by LordVersA** [comment]
how can I use this query to specify that search just work in Series and Movies indexes?

**Comment by matchish** [comment]
An example of an search with explicit index  `$client->search(['index' => 'products', 'body' => $body->toArray()]);`

**Comment by LordVersA** [comment]
I want to search in 2 indexes at the same time, how can I change this code to specify this for searing in 2 indexes?

**Comment by LordVersA** [comment]
I fix my problem with index parameter
thanks
```php
$result = Mixed::search('',function ($client,$body) use ($q){
				return $client->search([
										   "index" => ["prefix_movies","prefix_series"],
										   'body' => [
											  
											   "query" => [
												
												   "query_string" => [
													   
													   "query" => $q ,
													  
													   "fields" => [
														   "fa_title" ,
														   "en_title" ,
													   ] ,
													   "fuzziness" => "AUTO" ,
												   ] ,
											   ] ,
										   ] ,
										   
										   //"_source" => [
										   //	"id" ,
										   //] ,
										   "from" => 0 ,
										   "size" => 100 ,
									   ]);
			}
			)->within(implode(',', [
				(new Series())->searchableAs(),
				(new Movie())->searchableAs(),
			]))->get();
```
