### ISSUE TITLE
[Feature] how can I add Basic Auth (Username - Password) to configuration?

### ISSUE THREAD

**Issue by LordVersA** [matchish/laravel-scout-elasticsearch#186]
Recently I add basic auth to my elastic server, where should store my username and password for the authentication system in this package?

**Comment by matchish** [comment]
You can set host https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/host-config.html
Here https://github.com/matchish/laravel-scout-elasticsearch/blob/7740c6b01efdacb078cc90095cbe18584730d929/config/elasticsearch.php#L4
