### ISSUE TITLE
[BUG] illegal_argument_exception when using ElasticSearch 8.0

### ISSUE THREAD

**Issue by hamzamogni** [matchish/laravel-scout-elasticsearch#199]
**Describe the bug**
Running this package with elasticsearch 8.0 throws an error when importing models to es index.

**To Reproduce**
1. Create a model
2. Run a command `php artisan scout:import "\Model"`
4. See the following error

``` local.ERROR: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}]```

After some research and debugging, I believe es 8.0 removed the _type parameter.

**Version**
Laravel: 9.0
Scout: 9.4
laravel-scout-elasticsearch: 5.0

**Comment by hamzamogni** [comment]
Well after some more digging I figured that elasticsearch/elasticsearch should be updated, then I noticed `dev-master` branch that is using the newer version of elasticsearch/elasticsearch.

I will be using `dev-master` branch for now, I will report back if I hit any bugs or issue.

When are you planning to release the current dev-master? 

Thank you for your work on this package!

**Comment by matchish** [comment]
There is new 6.0.0 release that support es8
