### ISSUE TITLE
[BUG] Authorization

### ISSUE THREAD

**Issue by bastienu** [matchish/laravel-scout-elasticsearch#208]
**Describe the bug**
I am using a cloud app for my Elastic Search server.
I set the following information in my .env : 
```
ELASTICSEARCH_HOST="*****-elasticsearch.services.clever-cloud.com"
ELASTICSEARCH_SCHEME="http"
ELASTICSEARCH_PORT="80"
ELASTICSEARCH_PASS="********"
ELASTICSEARCH_USER="u*******"
ELASTICSEARCH_PATH=""
```

The information set are correct because I tried to connect with it using Elastron app, and it worked:
<img width="1319" alt="Capture d’écran 2022-06-13 à 16 19 26" src="https://user-images.githubusercontent.com/1685778/173375135-c2ae8101-4bec-49e3-8a57-ed5b48b10ed7.png">

But when I try to connect through my application, I have the following error:
```
401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/amendments_index/_search]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/amendments_index/_search]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\""]}},"status":401}
```

Do you know why?
What can I do ?

**Version**
- `"laravel/framework": "^8.12"`
- `"laravel/scout": "^9.4"`
- `"matchish/laravel-scout-elasticsearch": "^6.0"`

**Comment by matchish** [comment]
Can you connect to the server with https://github.com/elastic/elasticsearch-php ?

**Comment by bastienu** [comment]
Yes I can, the problem seems to be in config/scout.php:

```php
/*
|--------------------------------------------------------------------------
| Elasticsearch Configuration
|--------------------------------------------------------------------------
|
| Here you may configure your Elasticsearch settings.
|
*/
'elasticsearch' => [
    'hosts' => [
        // env('ELASTICSEARCH_HOST', 'localhost'),
        [
            'host'   => env('ELASTICSEARCH_HOST', 'localhost'),
            'port'   => env('ELASTICSEARCH_PORT', '9200'),
            'scheme' => env('ELASTICSEARCH_SCHEME', 'https'),
            'path'   => env('ELASTICSEARCH_PATH', '/elastic'),
            'user'   => env('ELASTICSEARCH_USER', 'username'),
            'pass'   => env('ELASTICSEARCH_PASS', 'password'),
        ]
    ],
],
```

The configurations values are not taken into account...

Where can I set my configuration is not in config/scout.php?

**Comment by bastienu** [comment]
When I  update the `register` method in `ElasticSearchServiceProvider.php` with : 
```php
/**
 * {@inheritdoc}
 */
public function register(): void
{
    $this->mergeConfigFrom(__DIR__.'/../config/elasticsearch.php', 'elasticsearch');

    $this->app->bind(Client::class, function () {
        return ClientBuilder::create()
            ->setHosts(['http://*****-elasticsearch.services.clever-cloud.com:80'])
            ->setBasicAuthentication('u******', '********')
            ->build();
    });

    $this->app->bind(
        'Matchish\ScoutElasticSearch\ElasticSearch\HitsIteratorAggregate',
        'Matchish\ScoutElasticSearch\ElasticSearch\EloquentHitsIteratorAggregate'
    );
}
```

It seems to be ok (even if I have an `index_not_found_exception`, but this is I think totally normal because I did not make a `scout:import`). 

So I think this package does not support Elasticsearch server with Basic Auth. Am I wrong?

**Comment by hkulekci** [comment]
@matchish https://github.com/matchish/laravel-scout-elasticsearch/pull/210 could you check this?

**Comment by hkulekci** [comment]
@bastienu, we merge a solution for the authorization. Could you check whether it is working for you?

**Comment by bastienu** [comment]
Hey, seems to be OK, thanks a lot !
