### ISSUE TITLE
[BUG] PHP 8.1 EloquentHitsIteratorAggregate TypeError

### ISSUE THREAD

**Issue by sfdjo435** [matchish/laravel-scout-elasticsearch#215]
When using a custom search method: `function (Client $client, Search $search)` you'll get a TypeError:
```php
Matchish\\ScoutElasticSearch\\ElasticSearch\\EloquentHitsIteratorAggregate::__construct(): Argument #1 ($results) must be of type array, Elastic\\Elasticsearch\\Response\\Elasticsearch given
```

**Comment by matchish** [comment]
php version? packages versions? scout, elasticsearch client

**Comment by sfdjo435** [comment]
PHP 8.1, ElasticSearch 8.3.3, laravel-scout-es V6.0.2, laravel/framework v9.25.1, laravel/scout v9.4.10

**Comment by amjadbanimattar** [comment]
@matchish We are facing the same problem. 
PHP 8.1, ElasticSearch 7.17.5, laravel-scout-es V6.0.2, laravel/framework v9.26.1, laravel/scout v9.4.10

**Comment by hkulekci** [comment]
@amjadbanimattar  @sfdjo435  Could you provide a sample custom search to test locally?

**Comment by hkulekci** [comment]
I think it is related to changes about the Elasticsearch search response. Older version was returning array but the new version is returning Response object. So, for the custom search `EloquentHitsIteratorAggregate` expecting array. I can create a PR for solution if you can give some sample to me.

**Comment by hkulekci** [comment]
This is a sample with an error : 

```
$results = Product::search('*',
    static function (Client $client, Search $body) {
        $highlight = new Highlight();
        $highlight->addField('name');
        $body->addHighlight($highlight);
        return $client->search(['index' => 'products', 'body' => $body->toArray()]);
    })->raw();
$iterator = new EloquentHitsIteratorAggregate($results);
dd($iterator);
```

Here the error :

```
[2022-08-30 02:43:58] local.ERROR: Matchish\ScoutElasticSearch\ElasticSearch\EloquentHitsIteratorAggregate::__construct(): Argument #1 ($results) must be of type array, Elastic\Elasticsearch\Response\Elasticsearch given, called in /laravel-scout-elasticsearch-example/app/Http/Controllers/ProductsController.php on line 52 {"exception":"[object] (TypeError(code: 0): Matchish\\ScoutElasticSearch\\ElasticSearch\\EloquentHitsIteratorAggregate::__construct(): Argument #1 ($results) must be of type array, Elastic\\Elasticsearch\\Response\\Elasticsearch given, called in /laravel-scout-elasticsearch-example/app/Http/Controllers/ProductsController.php on line 52 at /laravel-scout-elasticsearch-example/vendor/matchish/laravel-scout-elasticsearch/src/ElasticSearch/EloquentHitsIteratorAggregate.php:28)
```

I think this is what we are looking for. So the quick solution for this error is using `asArray()` method for raw search :

```
$results = Product::search('*',
    static function (Client $client, Search $body) {
        $highlight = new Highlight();
        $highlight->addField('name');
        $body->addHighlight($highlight);
        return $client->search(['index' => 'products', 'body' => $body->toArray()])->asArray();
    })->raw();
$iterator = new EloquentHitsIteratorAggregate($results);
dd($iterator);
```

I think the solution is that we need to force the users to return a specific type for the callback to be sure the returned data for `ElasticSearchEngine::performSearch()` method of the Builder. It should be returned specific type. The problem `performSearch` using `Builder::callback` internally. And there is no forcing for the return type in the Scout Builder inside.

**Comment by matchish** [comment]
There is another question. Why tests passes. Should fail as I understand

**Comment by hkulekci** [comment]
Here, in our library, we expect an array response from `raw()` method response. But there is no strict response type in `Laravel\Scout\Builder::raw()`. It is mentioned as mixed. So, raw queries start returning the response of callback directly. After version upgrade of ES Client, the search method starts returning `Response` object instead of an array directly. I tried to force the user to return the array for the callback of the raw search, but I could not find a short solution. So, the solution can be we can accept `Response` object or `array` at `EloquentHitsIteratorAggregate` constructor and resolve the object type to act according to it.

**Comment by hkulekci** [comment]
On the other hand, we had flaged `EloquentHitsIteratorAggregate` as `@internal`. To say this is internal, we need to create a `CustomBuilder` with extending`Laravel\Scout\Builder`. Maybe this can be another solution, too.

**Comment by matchish** [comment]
So in ci we don't use last elasticsearch lib?

**Comment by hkulekci** [comment]
I think so. the callback return needs to be an array. We need to mention that this is a BC Break of latest version.
