### ISSUE TITLE
[BUG] version:^4.0 (php: v7.4)   Class 'Elasticsearch\ClientBuilder' not found

### ISSUE THREAD

**Issue by VeOnBeat** [matchish/laravel-scout-elasticsearch#218]
**Describe the bug**
i am using php version 7.4 and i should use v4 package,
and i got this error, is there any way that i could fix it?

**Comment by VeOnBeat** [comment]
![image](https://user-images.githubusercontent.com/112238094/188264395-d6ba9399-55cf-4d5e-8538-48f5c9efe819.png)

**Comment by LordVersA** [comment]
same issue

**Comment by erfaansabouri** [comment]
Same issue!  PHP 7.4 ( Laravel 8 )

**Comment by hkulekci** [comment]
I think this is because of composer.json problem. In this version, composer.json file content is here : 

```
   "require": {
        "php": "^7.2|^7.3",
        "elasticsearch/elasticsearch": ">=7.2",
        "laravel/scout": "^8.0",
        "ongr/elasticsearch-dsl": "^7.0",
        "roave/better-reflection": "^3.3|^4.3"
    },
```

According to `"elasticsearch/elasticsearch": ">=7.2",` this part, composer will install version 8.4.1 today. So this means that the elasticsearch client won't work for version 4.0.5 of this library. :(

**Comment by LordVersA** [comment]
it worked thanks <3

**Comment by erfaansabouri** [comment]
Also worked for me, thank you. @hkulekci

**Comment by hkulekci** [comment]
I think we can close this issue, right? @erfaansabouri @LordVersA or @matchish, what do you think about sending a fix for older versions? I think we need to change `"elasticsearch/elasticsearch": ">=7.2",` with `"elasticsearch/elasticsearch": "^7.2",` and we need a new release for version 4.

**Comment by LordVersA** [comment]
that's a great idea

**Comment by VeOnBeat** [comment]
nice job
