### ISSUE TITLE
[BUG] Saving is trying to update fields from relationship

### ISSUE THREAD

**Issue by AiAe** [matchish/laravel-scout-elasticsearch#222]
I have Table "Offers" which has two more relations (Client and Broker) which are not indexed into ES. 
When I save the one thats indexed I get error "Bulk update error".

Checked the laravel log and noticed its trying to update the fields from one of the relationships.

![CleanShot 2022-10-28 at 15 17 09](https://user-images.githubusercontent.com/3695158/198585027-bcc0296b-48fd-4a86-883e-49cf04de75fb.png)

Log file:

[laravel-2022-10-28.log](https://github.com/matchish/laravel-scout-elasticsearch/files/9888348/laravel-2022-10-28.log)

**Versions**
Laravel: 9.6
Scout: 9.4
Scout Elasticsearch: 6.0
Elasticsearch: 8.4.3

**Comment by matchish** [comment]
https://laravel.com/docs/master/scout#configuring-model-indexes
Did you check what data contains your model when you call `toArray` method on it? Think about to configure `toSearchableArray` method

**Comment by AiAe** [comment]
> https://laravel.com/docs/master/scout#configuring-model-indexes Did you check what data contains your model when you call `toArray` method on it? Think about to configure `toSearchableArray` method

Yes I did, everything there was normal.

This is my toSearchableArray code:
`public function toSearchableArray()
    {
        $array = $this->toArray();

        // Load meta
        $offer_meta = AgencyOfferMeta::where('agency_id', $array['agency_id'])
            ->where('agency_offer_id', $array['id'])->get();

        foreach ($offer_meta as $meta)
        {
            if(in_array($meta['key'], $array)) continue;
            $array[$meta['key']] = $meta['value'];
        }

        return $array;
    }`

**Comment by AiAe** [comment]
I tried to also remove the loading of meta that I have there, it did not resolve the issue. 
Since when i tried to remove the 2 relationships i mentioned above it resolved the problem, but I need them.

**Comment by matchish** [comment]
Maybe mappings for your data is wrong. You can try to log request that you're trying to send to elastic and then to check if it match to yours mappings. https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/enabling_logger.html
