### ISSUE TITLE
[Feature] How to override queue timeout?

### ISSUE THREAD

**Issue by amcsi** [matchish/laravel-scout-elasticsearch#229]
My queue worker's default [timeout](https://laravel.com/docs/9.x/queues#timeout) is at 60 seconds which is ideal for most tasks.

But I have a lot of posts to make searchable for ElasticSearch and it can take up to 300 seconds to run, so I want to set the job timeout to that amount. How can I do that?

I think I would need to somehow add `public $timeout = 300;` to `\Matchish\ScoutElasticSearch\Jobs\QueueableJob`, but I can't make changes to that class that's part of the library.

**Comment by matchish** [comment]
Feel free to open PR that set value for timeout from config file

**Comment by hkulekci** [comment]
What do you think about setting this configuration inside the `[ImportCommand.php:52](https://github.com/matchish/laravel-scout-elasticsearch/blob/master/src/Console/Commands/ImportCommand.php#L52)`. We already reaching config in this command and we can put as :

```
        if (config('scout.queue')) {
            $job = (new QueueableJob())->chain([$job]);
            $job->timeout = config('elasticsearch.queue.timeout', 60);
        }
```

**Comment by matchish** [comment]
Looks perfect) Thank you @hkulekci

**Comment by matchish** [comment]
released. Thank you guys) @hkulekci @amcsi
