### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by adrianpaiva1** [matchish/laravel-scout-elasticsearch#235]

**Comment by matchish** [comment]
https://github.com/laravel/scout/pull/696/files

Looks like not too much changes needed. Feel free to send a PR

**Comment by hkulekci** [comment]
We need to upgrade the `"orchestra/testbench": "^6.18",` also for this support. I did not check yet why we depend on this library. I am looking for this upgrade if you don't look @adrianpaiva1

**Comment by matchish** [comment]
orchestra/testbench package to have tests that depends on laravel. this repo laravel package that's why we have it. I think we can update, I don't see any blockers for it

**Comment by matchish** [comment]
I believe we can switch to "orchestra/testbench": "^6.17|^7.0|^8.0", the same that laravel/scout use

**Comment by matchish** [comment]
@adrianpaiva1 Released. Could you give a feedback? Many thanks to @hkulekci

**Comment by vrusua** [comment]
@matchish Hi Sergey,
the scout 10.0 is released, could you please update dependencies from laravel/scout: `^8.0|^9.0|^10`. Thanks.

**Comment by matchish** [comment]
@vrusua thanks for the PR. released
