### ISSUE TITLE
[Feature] v5 with forked handcraftedinthealps/elasticsearch-dsl

### ISSUE THREAD

**Issue by m-lotze** [matchish/laravel-scout-elasticsearch#236]
Could you please add a release for v5 with handcraftedinthealps/elasticsearch-dsl instead of ongr/elasticsearch-dsl? 
ongr/elasticsearch-dsl requires symfony 5 and this prevents an update to laravel 10, which requires symfony 6.

**Comment by matchish** [comment]
Hey. Feel free to send a PR

**Comment by hkulekci** [comment]
I think here, we need to initialize a v5.x branch, and we need to release version 5.x from that branch. We can initialize that branch from tags, what do you think? @matchish @m-lotze

**Comment by hkulekci** [comment]
This is the latest 5.x tag https://github.com/matchish/laravel-scout-elasticsearch/releases/tag/v5.0.2

**Comment by matchish** [comment]
Completely agree

**Comment by m-lotze** [comment]
I have forked the repository, created a branch from v5.0.2 and committed the changes to composer.json. 

https://github.com/m-lotze/laravel-scout-elasticsearch/tree/v5

If you could create a branch for v5, i can submit a pull request.

**Comment by matchish** [comment]
@m-lotze I've created 5.x branch could you  push the PR?

**Comment by m-lotze** [comment]
Sure. Repushed the pull request to 5.x.

**Comment by matchish** [comment]
merged

**Comment by m-lotze** [comment]
Great. Thank you.
