### ISSUE TITLE
[BUG] Class Elasticsearch\Client not found

### ISSUE THREAD

**Issue by soeurngsar** [matchish/laravel-scout-elasticsearch#258]
**Describe the bug**
In Laravel v10.x I'm upgrade [laravel-scout-elasticsearch](https://github.com/matchish/laravel-scout-elasticsearch) to v7.3 as you mention that it is support Laravel Scout v10.x as well. After composer update and I make a test to query from Elastic it show the error Class Elasticsearch\Client not found.

As I check on your source code it is required [elasticsearch-php](https://github.com/elastic/elasticsearch-php) v8.x and [elasticsearch-php](https://github.com/elastic/elasticsearch-php) has changed the name space from Elasticsearch to 
Elastic\Elasticsearch which make your code not working.

**To Reproduce**
$client = app()->make(Client::class);
$data = $client->msearch($params);

**Expected behavior**
It should get the result from ElasticSearch.

**Additional context**
I'm using msearch from ElasticSearch.

**Version**
Laravel version 10.x, Scout version 10.x

**Comment by hkulekci** [comment]
I could not reproduce this error. Could you share the complete trace of the error? It should be related to [ES upgrade](https://github.com/matchish/laravel-scout-elasticsearch/pull/198), not scout upgrade. If you can share full trace we can try to find real problem.

**Comment by hkulekci** [comment]
Hey @soeurngsar, do you have any update on this issue?

**Comment by soeurngsar** [comment]
Hi @hkulekci , Thank for your feedback. I found that this issue has been resolved for some reason.
