### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by jackraymund** [matchish/laravel-scout-elasticsearch#265]
Hello,
is there chance to get upgrade this library to support PHP8.3?
laravel-scout-elasticsearch 7.4 needs package roave/better-reflection ^4.3|^5.0
But to support 8.3 roave/better-reflection needs to be ^6.18

**Comment by matchish** [comment]
Hey, feel free to send a PR to upgrade roave/better-reflection if it will pass tests we can make a new release

**Comment by matchish** [comment]
released. thanks @jackraymund
