### ISSUE TITLE
Getting error "Elasticsearch\Common\Exceptions\BadRequest400Exception" on import command?

### ISSUE THREAD

**Issue by Don404** [matchish/laravel-scout-elasticsearch#27]
Hello, thank you for this package!! I am not sure why am I getting the following error in terminal when I try to do `php artisan scout:import`

`Elasticsearch\Common\Exceptions\BadRequest400Exception  : {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [id]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: No handler for type [keyword] declared on field [id]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [id]"}},"status":400}`

I apologise if the issue is with me.

**Comment by matchish** [comment]
Helle, thank you for your interest in the package)

What is package version and elasticsearch version?

**Comment by matchish** [comment]
Closed because of no response

**Comment by martin-ro** [comment]
I have the same error. Not sure how to setup `config/elasticsearch.php`. I just used the example config.

**Comment by matchish** [comment]
The package tested only with elasticsearch 6 and above. Try to upgrade your elasticsearch if it's an option for you.

**Comment by medspec** [comment]
i also have this error.

running "dev-elasticsearch-7"
and elasticsearch version : 7.1.1

**Comment by medspec** [comment]
sorry found it.. 
is switched to the 7 version, but didnt update the config file
