### ISSUE TITLE
How to use the latest version of this package with Elasticsearch 7?

### ISSUE THREAD

**Issue by davimug** [matchish/laravel-scout-elasticsearch#271]
Is it possible to use the latest version of this package with Elasticsearch 7? From the readme, it seems yes but the elasticsearch version is locked in the composer config. Could anyone point me in the right direction?

Thanks

**Comment by matchish** [comment]
Don't remember but I think the package will be broken if you downgrade elasticsearch client.

**Comment by matchish** [comment]
Just realized that tests run against ES7 https://github.com/matchish/laravel-scout-elasticsearch/blob/9b675df4be7b0dd4a9599860bd5cb6def1a75664/.github/workflows/test-application.yaml#L25
so you can try to use the package with latest version.

**Comment by davimug** [comment]
Okay, seems to work with that version :) I was getting a strange error regarding the headers used - thanks!
