### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by medspec** [matchish/laravel-scout-elasticsearch#28]
Is there a way to add Highlight to search result?

**Comment by matchish** [comment]
You can use any feature provided by https://github.com/ongr-io/ElasticsearchDSL package
Here an example of using highlight https://stackoverflow.com/questions/56720692/add-highlight-using-ongr-io-elasticsearchdsl-package/56729546#56729546

Just put that code into callback of a search method
```
Product::search('title:this OR description:this) AND (title:that OR description:that', function ($client, Search $body) {
            $higlight = new Highlight();
            $higlight->addField('title');
            $body->addHighlight($higlight);
            return $client->search(['index' => 'products', 'body' => $body->toArray()]);
})->raw();
```

**Comment by vaishnavmhetre** [comment]
> You can use any feature provided by https://github.com/ongr-io/ElasticsearchDSL package
> Here an example of using highlight https://stackoverflow.com/questions/56720692/add-highlight-using-ongr-io-elasticsearchdsl-package/56729546#56729546
> 
> Just put that code into callback of a search method
> 
> ```
> Product::search('title:this OR description:this) AND (title:that OR description:that', function ($client, Search $body) {
>             $higlight = new Highlight();
>             $higlight->addField('title');
>             $body->addHighlight($higlight);
>             return $client->search(['index' => 'products', 'body' => $body->toArray()]);
> })->raw();
> ```

I applied this solution but this didn't sort the output by Score, which it usually does.

**Comment by ganicus** [comment]
Is there a way to take this raw query and pass it back into a laravel collection that includes the highlights? Currently the raw query response places the "highlight" outside of the _source field that is aggregated into eloquent models via the map function in the custom scout engine.

**Comment by matchish** [comment]
You can implement your own `EloquentHitsIteratorAggregate` and pass raw results there.
https://github.com/matchish/laravel-scout-elasticsearch/blob/34a53de7e72cae1fd7305955c7e6b846eabbc3de/src/Engines/ElasticSearchEngine.php#L106

I have plans to inject EloquentHitsIteratorAggregate using DI to be able to use different implementations, but now I'm working on another feature. Feel free to send PR)

**Comment by matchish** [comment]
https://github.com/matchish/laravel-scout-elasticsearch/tree/elasticsearch-7#working-with-results

**Comment by booni3** [comment]
An example of merging highlights into  a custom hits aggregator. It may not be best practice... but is working. Comments welcome.

```php
/**
 * Retrieve an external iterator.
 * @link https://php.net/manual/en/iteratoraggregate.getiterator.php
 * @return Traversable An instance of an object implementing <b>Iterator</b> or
 * <b>Traversable</b>
 * @since 5.0.0
 */
public function getIterator()
{
    $hits = collect();
    if ($this->results['hits']['total']) {
        $raw = collect($this->results['hits']['hits']);
        $models = $this->collectModels($raw);
        $models = $this->getEloquentArray($raw, $models);
        $hits = $this->mergeHighlightsIntoModels($models, $raw);
    }

    return new \ArrayIterator($hits);
}

private function collectModels($hits)
{
    return collect($hits)->groupBy('_source.__class_name')
        ->map(function ($results, $class) {
            $model = new $class;
            $builder = new Builder($model, '');
            if (! empty($this->callback)) {
                $builder->query($this->callback);
            }
            /* @var Searchable $model */
            return $models = $model->getScoutModelsByIds(
                $builder, $results->pluck('_id')->all()
            );
        })
        ->flatten()->keyBy(function ($model) {
            return get_class($model).'::'.$model->getScoutKey();
        });
}

private function mergeHighlightsIntoModels($models, $raw)
{
    return collect($models)->map(function($model) use($raw){
        $raw = collect($raw)
            ->where('_source.__class_name', get_class($model))
            ->where('_source.id', $model->id)
            ->first();

        foreach($raw['highlight'] ?? [] as $key => $highlight){
            $model->setAttribute($key, $highlight[0]);
        }

        return $model;
    })->all();
}

private function getEloquentArray($hits, $models)
{
    return collect($hits)->map(function ($hit) use ($models) {
        $key = $hit['_source']['__class_name'].'::'.$hit['_id'];
        return isset($models[$key]) ? $models[$key] : null;
    })->filter()->all();
}
```

**Comment by XieXiaoSa** [comment]
Search results are sorted by ID but id is segmented. What should I do

**Comment by mondherinfo** [comment]
how can i add score to fields, best score will be in the begin

**Comment by matchish** [comment]
Learn it here https://github.com/ongr-io/ElasticsearchDSL

**Comment by fengci** [comment]
@booni3 https://github.com/matchish/laravel-scout-elasticsearch/issues/28#issuecomment-583736966 

Hello, how do I use it?
