### ISSUE TITLE
Driver [Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine] not supported

### ISSUE THREAD

**Issue by obsessen** [matchish/laravel-scout-elasticsearch#32]
Hello,

I set the env variable SCOUT_DRIVER to `Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine` as stated in the readme. Is this setting correct? 

I get this error:
`Driver [Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine] not supported`.

While looking at the default scout config I noticed that this env variable is a string that references a config array lower in the same file.

**Comment by obsessen** [comment]
Ok, my mistake. I had to add two service providers to the app.php config:

- Matchish\ScoutElasticSearch\ScoutElasticSearchServiceProvider::class,
- Matchish\ScoutElasticSearch\ElasticSearchServiceProvider::class

Maby this should be stated in the readme more clearly.

**Comment by matchish** [comment]
Hello) Thanks for the feedback! If you have any idea how to improve the readme, feel free to send PR.
