### ISSUE TITLE
scout:import don't throwing errors when elastic return error (wrong format date or else)

### ISSUE THREAD

**Issue by strangetin** [matchish/laravel-scout-elasticsearch#37]

**Comment by matchish** [comment]
Thanks for the feedback! Would you implement a minimal test case?

**Comment by strangetin** [comment]
Unfortunately now there is absolutely no time. I encountered this “mistake” quite by accident.
If you specify an incorrect date format in the mapping. For example, like this:
```php
'tags' => [
    'properties' => [
        'id' => [
            'type' => 'integer'
        ],
        'title' => [
            'type' => 'text'
        ],
        'created_at' => [
            'type' => 'date',
            'format' => "yyyy-MM-dd||epoch_millis"
        ]
    ]
],
```
And in laravel, as you know, timestamp fields format is yyyy-MM-dd HH: mm: ss
When I import all searchable models via scout:import, it succesfully imported, but elastic show 0 docs.

And if I dump this 
```php
dd($this->elasticsearch->bulk($params->toArray());
```
in update function of ElasticSearchEngine class, bulk function return elasticsearch errors.

**Comment by matchish** [comment]
That's enough to reproduce the bug. Thanks a lot!

**Comment by matchish** [comment]
Fixed
