### ISSUE TITLE
Question. Is there a way to include results from multiple indices in one call? 

### ISSUE THREAD

**Issue by mpdx** [matchish/laravel-scout-elasticsearch#38]
Hello, Sergey!

Thanks for very handy package! Really appreciated. First I will briefly describe my use-case. I used `Mixed::class` as simple as follows:

```
Mixed::search('foobar')
    ->within('one', 'two')
    ->get()
```
(TBH I'm aware of paginator available to increase the limit, and in fact I'm using it instead of returning collection like in the example but it doesn't matter in explaining the case)
 
☝️ The code above by default returns EloquentCollection of 10 models. It doesn't matter how many indices I pass to `within` method it will always give back first 10 models of the first index ('one' in this example).

I'm looking for an elegant solution to limit results returned from each index, i.e I would like to have an EloquentCollection of - for example - `X` elements from each index. The only solution I came to is to return everything and transform collection later on (using groupBy's/limits etc) but obviously it doesn't count as efficient and elegant solution since I have around 3 million records in ES. I hoped maybe you could have some clever trick to share with 😅 

Thanks for looking into it! 🙏 
all the best!

**Comment by matchish** [comment]
Hello) Thanks a lot for the feedback!
To limit results for each index you should use multi-search https://discuss.elastic.co/t/searching-multiple-index-types-or-indexes-limit-results-by-type/583
I have plans to implement syntax like 
```
Mixed::search([
    Ticket::search('foobar')->paginate(3),
    City::search('baz')->paginate(3)
])->get();
```

But now you have only one option, it's building multi-search with callback
https://github.com/matchish/laravel-scout-elasticsearch#search

**Comment by mpdx** [comment]
Thanks! Seems that is what I was looking for 🙇
