### ISSUE TITLE
Custom config?

### ISSUE THREAD

**Issue by dragonfire1119** [matchish/laravel-scout-elasticsearch#4]
I was looking at this package to replace a custom solution. Are you planning on creating a default config to show people how to create mappings?

**Comment by matchish** [comment]
I guess it does make sense to add the default config for demo. I'll add it tomorrow.

**Comment by dragonfire1119** [comment]
@matchish I got this package working nicely on one of my projects! Thank you! The zero downtime is nice as well!

**Comment by matchish** [comment]
Thank you too) I've add default config to `config` branch. It passing all tests but I'm not ready to merge it to `master` right now.

**Comment by dragonfire1119** [comment]
It's not a problem for me. I just thought it would be nice for others that don't know elastic search.
