### ISSUE TITLE
Indices aren't configured correctly when you dont use the `scout:import` command

### ISSUE THREAD

**Issue by jdbolts** [matchish/laravel-scout-elasticsearch#46]
If you do not use the `scout:import` command, indexes are no longer appended with the `time()`. Which results in the following error:

````
{
   "error":{
      "root_cause":[
         {
            "type":"index_not_found_exception",
            "reason":"no such index",
            "resource.type":"index_or_alias",
            "resource.id":"index_name",
            "index_uuid":"_na_",
            "index":"index_name"
         }
      ],
      "type":"index_not_found_exception",
      "reason":"no such index",
      "resource.type":"index_or_alias",
      "resource.id":"index_name",
      "index_uuid":"_na_",
      "index":"index_name"
   },
   "status":404
}
````

**Comment by matchish** [comment]
How do you create the index?

**Comment by jdbolts** [comment]
They are created automatically when using importing the data. If you do not use `scout:import` and save a new model the index is then also automatically created but without the timestamp at the end of the index name

**Comment by matchish** [comment]
Timestamp doesn't matter. Alias of an index is an identifier for search. Could create a minimally test to reproduce the issue?

**Comment by jdbolts** [comment]
If you create a simple Laravel application and install this package. Then create a simple model (let's say users) with a seeder. When you run the seeder an index will be created (`users_index`). However, if you don't run the seeder and instead run the artisan command `scout:import` before running the seeder, you will get an index created which will be `users_index_TIMESTAMP`. This causes issues when you have an empty application and do not run the scout import initially.

**Comment by matchish** [comment]
The index `users_index_TIMESTAMP` has an alias `users_index` so it can be anything `user_index_uuid` for example. I'll test the case later but now I can recommend using [User::disableSearchSyncing()](https://github.com/laravel/scout/blob/e1edf0d58e160a686263540aab0a70c0cba9981d/src/Searchable.php#L200) before seeding and `User::enableSearchSyncing()` after. Then you can run `scout:import`

**Comment by jdbolts** [comment]
I got around this issue by calling the `scout:import` on my migration before any data is imported. This way, the indices are created correctly and then when the seeder is called, or a model is created, the index already exists so is added correctly using the alias.

**Comment by vrusua** [comment]
@matchish 

Hi Sergey,

sorry for pushing the legacy record, but I'm still getting the same issue on V6.0.2: 

The missing index is creating correctly (with the alias and named timestamp) using the ```scout:import``` only when resending all the data. However, when we're calling some Eloquent updates, or running ```searchable()``` explicitly - the newly created index appears without the alias and named timestamp.

Is there any way to sort out this?

This option will be useful when we don't need to sync full the data to Elastic but just part only. Thanks.


Cheers,
Ruslan

**Comment by vrusua** [comment]
@matchish  or maybe some guide how to implement ```createIndex()``` for the ```scout:index``` option?

**Comment by matchish** [comment]
@vrusua Hey) Actually you're right. The package missing scout:index and scout:delete-index commands. I believe they have to be added here as well. The issue with scout-index it accept index name not a model and we need settings and mappings for new index and scout:index don't have those parameters. If you want to index only part of your data you can create a model that will represent that part by adding a global scope to it. Then just import that model. Updates of that model will go to the index as well.

**Comment by matchish** [comment]
@vrusua Feel free to implement createIndex method if you think that custom model can't solve your issue https://github.com/matchish/laravel-scout-elasticsearch/issues/223

**Comment by vrusua** [comment]
> @vrusua ... If you want to index only part of your data you can create a model that will represent that part by adding a global scope to it. Then just import that model. Updates of that model will go to the index as well.

Yeah, got it, thanks for the workaround and a quick reply.

**Comment by dorep** [comment]
@vrusua I dont really understand the work around. Can you please explain?

**Comment by matchish** [comment]
@dorep Are you interesting in partial import of some data?

**Comment by dorep** [comment]
Hello, Thanks for the reply! My scenario is this: I have an existing app deployed in production and elastic index set up (with your import commands), all working. And then I add a new model to the application (it has a migration, new table, etc.). Index for this model does not exist at this time. When a user saves this new model for the first time after deployment, our model observer calls searchable() function, and creates a new search index.

The problem is, that this created index does not use settings that are defined in the `config/elasticsearch.php` (in my case: replica count, analysis->analyzer).

**Comment by matchish** [comment]
@dorep To me your case falls into base use case for importing

Before model observer calls searchable() function run import command for that model
https://laravel.com/docs/master/scout#indexing
`php artisan scout:import "App\Models\NewModel"`
You can run it from code as well https://laravel.com/docs/11.x/artisan#programmatically-executing-commands
