### ISSUE TITLE
WhereIn Methods and others

### ISSUE THREAD

**Issue by mackhankins** [matchish/laravel-scout-elasticsearch#47]
> To be fully compatible with original scout package, this package does not add new methods.

I really need a `whereIn('id', $array)` method for a project I'm working on.  Is there a way I can extend the Builder or run a more complex query to accomplish?

**Comment by mackhankins** [comment]
I created a macro for this since right now `whereIn` is the only method I need.  However, I think there is a cause for extending the capabilities of scout for the chose engine.  Algolia created scout-extended for example.

```php
        Builder::macro('whereIn', function ($field, array $value) {
            foreach ($value as $val) {
                $this->where($field, $val);
            }

            return $this;
        });
```

Full Gist for others.
https://gist.github.com/mackhankins/454d4114e34d5c885fd66fcdf0081550

**Comment by mackhankins** [comment]
Just wanted to add to this, the DSL way is Terms query.  It accepts an array and works perfectly.

http://docs.ongr.io/ElasticsearchDSL/Query/TermLevel/Terms

**Comment by matchish** [comment]
https://github.com/laravel/scout/releases/tag/v9.2.1 
Scout support wherein now
If anyone want to implement whereIn in the engine feel free to pr. Don't forget to add tests for it

**Comment by Orest-Divintari** [comment]
I started working on the whereIn but when I tried to git clone the repo, the tests folder was missing. Any idea why this happens ?

**Comment by matchish** [comment]
No idea. Should clone with tests
![image](https://user-images.githubusercontent.com/818563/126474067-0773340c-5113-4a36-9650-bf537b8dd9b1.png)

**Comment by matchish** [comment]
Try to fork first
![image](https://user-images.githubusercontent.com/818563/126474309-2d0d9a9b-af18-450c-8755-c8599d922ed4.png)

**Comment by Orest-Divintari** [comment]
It works after I forked.

But now when I run `docker-compose up` I get the following error

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: target stage php- could not be found`

After I googled the error, I found that the issue that most people had was that their docker file was named `dockerfile` instead of `Dockerfile` but in your repo you don't have that problem.

Have you faced this issue before ?

**Comment by matchish** [comment]
You can find available make commands here
https://github.com/matchish/laravel-scout-elasticsearch/blob/master/Makefile

**Comment by Orest-Divintari** [comment]
> Use make command instead
> https://github.com/matchish/laravel-scout-elasticsearch/blob/master/CONTRIBUTING.md

can't make it work with `make`

I get this error `sysctl: unknown oid 'vm.max_map_count' when I run `sysctl -w vm.max_map_count=262144`

I found some  "solutions" but I run into a new issue every time.

**Comment by matchish** [comment]
What os do you have?

**Comment by Orest-Divintari** [comment]
macOS Big Sur

**Comment by matchish** [comment]
Remove this line
https://github.com/matchish/laravel-scout-elasticsearch/blob/86aa41fddb1fd27fb7bd0f959c44564acc23355b/Makefile#L24
It related to linux only.

**Comment by Orest-Divintari** [comment]
now I get the same error I got when I ran `docker-compose up`

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: target stage php- could not be found
make: *** [up] Error 17`

I tried again about 7 solutions to this error but none solved the issue.

**Comment by matchish** [comment]
Looks like you need to rename https://github.com/matchish/laravel-scout-elasticsearch/blob/master/.env.example to .env

**Comment by matchish** [comment]
I mean you don't have .env find

**Comment by Orest-Divintari** [comment]
Was my pull request rejected ? 
If yes, could you please let me know why so I can fix it ?

**Comment by matchish** [comment]
Which one? I didn't reject any?

**Comment by Orest-Divintari** [comment]
can you see it now ?

**Comment by matchish** [comment]
Closed here https://github.com/matchish/laravel-scout-elasticsearch/pull/177
Great job @Orest-Divintari. BIg thanks for your contribution)
