### ISSUE TITLE
Search only returns first 10 results

### ISSUE THREAD

**Issue by bucalexis** [matchish/laravel-scout-elasticsearch#50]
Why always a search return the first 10 results and how I can iterate over the next page or increase the page size?

**Comment by mackhankins** [comment]
I think the two ways to manipulate this are `paginate(25)` and `setSize(25)`.

http://docs.ongr.io/ElasticsearchDSL/HowTo/CustomParameters

**Comment by bucalexis** [comment]
Thank you for the setSize example, it worked. But when using the paginate method Laravel (5.7)  throws an Exception "Unsupported operand types". I think is most readable using the paginate rather than passing always a callback function if I only need to increase  the page size.

<img width="799" alt="Captura de pantalla 2019-09-13 a la(s) 11 42 34 a  m" src="https://user-images.githubusercontent.com/11410614/64886682-9b54d580-d61b-11e9-8880-9c90acc4bb47.png">

**Comment by bucalexis** [comment]
I created a [pull request](https://github.com/matchish/laravel-scout-elasticsearch/pull/51) fixing this error.

**Comment by matchish** [comment]
@bucalexis Seems you are using `Elasticsearch 7` and `master` branch together. If you want to use `ES7` you should use `elasticsearch-7` branch instead.

https://github.com/matchish/laravel-scout-elasticsearch/blob/c13b00224dcb8daf29f2bc0dbff27efc8f2e0657/src/Engines/ElasticSearchEngine.php#L115
