### ISSUE TITLE
Elasticsearch\Common\Exceptions\BadRequest400Exception

### ISSUE THREAD

**Issue by webhaikal** [matchish/laravel-scout-elasticsearch#53]
Error:
` {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."}],"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."},"status":400}`

Elasticsearch Info:
```
{
  "name" : "homestead",
  "cluster_name" : "homestead",
  "cluster_uuid" : "Sm6BquEUSsWCLDusQk-iyg",
  "version" : {
    "number" : "7.3.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "1c1faf1",
    "build_date" : "2019-09-06T14:40:30.409026Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

This is running `matchish/laravel-scout-elasticsearch:^2.0`

**Comment by matchish** [comment]
`matchish/laravel-scout-elasticsearch:^2.0` for `Elasticsearch 6`
Try [elasticsearch-7](https://github.com/matchish/laravel-scout-elasticsearch/tree/elasticsearch-7) branch

**Comment by webhaikal** [comment]
> `matchish/laravel-scout-elasticsearch:^2.0` for `Elasticsearch 6`
> Try [elasticsearch-7](https://github.com/matchish/laravel-scout-elasticsearch/tree/elasticsearch-7) branch

Just tried, still the same error

**Comment by mackhankins** [comment]
The config changes in the elasticsearch-7 branch.

https://github.com/matchish/laravel-scout-elasticsearch/blob/elasticsearch-7/config/elasticsearch.php

**Comment by webhaikal** [comment]
Alright fixed. Thank you.
