### ISSUE TITLE
Empty models are being imported

### ISSUE THREAD

**Issue by reinierkors** [matchish/laravel-scout-elasticsearch#55]
Hello,

Right now I'm returning an empty array in `toSearchableArray()` 

These empty models are still being indexed. I was wondering if it's possible to exclude these from being indexed?

Thanks

**Comment by matchish** [comment]
Hello,

Can you implement a test to reproduce the bug?

Regards

**Comment by damianbal** [comment]
Looks like there isn't a check for empty toSearchableArray, so if it returns empty array it will be indexed, I'm working on that, I will create PR soon.

**Comment by matchish** [comment]
@reinierkors @damianbal I've understood what problem you try to solve. And I believe there is a solution in the original scout package. `Searchable` trait has `shouldBeSearchable` method.

So you can override the method in your model, and model will be not indexable if `toSearchableArray` return empty array
```
public function shouldBeSearchable()
{
    return !empty($this->toSearchableArray());
}
```

**Comment by reinierkors** [comment]
When I use
```php
public function shouldBeSearchable()
{
    return false;
}
```

and I remove the index and run `php artisan scout:import` every model still gets imported. It doesn't seem to get checked for scout:import.

**Comment by matchish** [comment]
@reinierkors I've added test for unsearchable models and it [pass](https://github.com/matchish/laravel-scout-elasticsearch/runs/249395440). Could you implement a fail test?

https://github.com/matchish/laravel-scout-elasticsearch/commit/258f310af604270d7400f34a08ae07f0ec1e035f

**Comment by reinierkors** [comment]
I have been digging into the cause of my issues. And it seems to be a couple of things:

- My queue worker sometimes timed out due to memory limitations. I didn't notice this at first, because it just gracefully exits without any notice. 

- Because of the timeout I still had jobs in my Redis queue with the old model data before I added `shouldBeSearchable()`. So after clearing my Redis queue, and running the import again (and fixing missing relations), everything seems to be working fine again.

Thanks a lot for helping out.
