### ISSUE TITLE
Searching empty string

### ISSUE THREAD

**Issue by jmverges** [matchish/laravel-scout-elasticsearch#57]
Hi there,

here we are doing a multi filter with aggregations and in some cases the search query string is nothing and what is valuable in those cases is all the logic inside the callback function. 

Does anybody know if there is a way to avoid getting 0 results when $string is ''?;

```
Product::search($stringEmptySometimes, function($client, $body) {
//all the valuable logic ...
});
```

Regards

**Comment by matchish** [comment]
Hello.

Try to use an asterisk instead of an empty string.

```
$stringEmptySometimes = empty($stringEmptySometimes) ? '*' : $stringEmptySometimes; 
```

**Comment by jmverges** [comment]
Thanks!
