### ISSUE TITLE
[3.0] Merge elasticsearch-7 branch into master

### ISSUE THREAD

**Issue by matchish** [matchish/laravel-scout-elasticsearch#62]

**Comment by aaronhuisinga** [comment]
Hey @matchish, what still has to be done before this is ready to merge? I can help resolve any remaining issues.

**Comment by mackhankins** [comment]
Same, would love to get off the branch for my 3 current projects...  What's the hold up? 💯

**Comment by matchish** [comment]
Hey @aaronhuisinga @mackhankins. Thank you for offering to help! To merge `elasticsearch-7` branch you just should resolve conflicts and be sure that all tests passes. I'm on vacation now. That's why I can't do it. So, it will be great if you merge the branch to master. I'll assign the issue to you.

**Comment by matchish** [comment]
Hey, @aaronhuisinga @mackhankins  Any ETA?

**Comment by mackhankins** [comment]
I'm out of town this whole week and we roll out our big project next week or two.  I'm swamped, sorry.

**Comment by matchish** [comment]
@mackhankins No problem, feel better)

**Comment by matchish** [comment]
Done
