### ISSUE TITLE
env ELASTICSEARCH_HOST var doesn't work when config is cached

### ISSUE THREAD

**Issue by dragonfire1119** [matchish/laravel-scout-elasticsearch#7]
When I cache my config the env helper always returns null since Laravel 5.2. So you would need to add the ELASTICSEARCH_HOST to a config for this to work correctly.

**Comment by matchish** [comment]
Thanks for issue report! I'm going split service provider to extract elasticsearch bootstrapping. The service provider with elasticsearch will be disabled by default. And of course I'll fix the issue with the cached config in a new update

**Comment by dragonfire1119** [comment]
@matchish Thanks for getting back to me. Ya I ran into this issue on going production on one of my projects. I thought I was going to have to fork it. So your plan is to let the developer set the elasticsearch bootstrapping instead of the package?

**Comment by matchish** [comment]
Yes, there are other packages what bootstrap elasticsearch and I think this package should focus on other things. Here will be basic configured elasticsearch client for developers who need a quick start, but it will be disabled by default. I've pushed fix to dev branch [split-sprv](https://github.com/matchish/laravel-scout-elasticsearch/tree/split-sprv) . But I'm not ready to merge it right now.

**Comment by matchish** [comment]
FIxed
