### ISSUE TITLE
Bulk update error

### ISSUE THREAD

**Issue by dragonfire1119** [matchish/laravel-scout-elasticsearch#71]
I just updated to 2.0.3 & I get bulk update error on all my PHPUnit tests. I went back to 2.0.2 & it's fine.

**Comment by matchish** [comment]
All tests passes https://travis-ci.com/matchish/laravel-scout-elasticsearch/builds/135235020

Do you mean I should bump version to `3.0.0` because of broken backward compatibility?

**Comment by dragonfire1119** [comment]
@matchish Probably so since it's not working on my end for some reason. Like I said something changed between 2.0.2 - 2.0.3 that's got this error coming up. It would be nice if the error was more descriptive of what's happening?

**Comment by matchish** [comment]
I've published fix in 2.0.4 Let me know pls does it help or not

**Comment by dragonfire1119** [comment]
@matchish Thanks for the fast updates. I'll test it soon... :)

**Comment by matchish** [comment]
Closed as inactive. Feel free to reopen if it still is the case.

**Comment by dragonfire1119** [comment]
@matchish I downloaded 3.0.0 great work it shows me the server error no! I learned that it was a forbidden error so I ran 
`curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'`
 & it fixed. I just couldn't see the error before for some reason.

Sorry for getting to this late it's been busy for the holidays.

**Comment by faniuta** [comment]
i have same error in 
`        "matchish/laravel-scout-elasticsearch": "^7.2",
`i run this command
`sail artisan scout:import "App\Models\Product"
`
can you help me??
![Screenshot from 2023-07-14 22-47-58](https://github.com/matchish/laravel-scout-elasticsearch/assets/10582970/72888c80-4c39-4343-b848-2998774e8955)

**Comment by matchish** [comment]
@faniuta could you open new ticket with exception details?
