### ISSUE TITLE
Search results return full model, not what the index contains.

### ISSUE THREAD

**Issue by bsaunders73** [matchish/laravel-scout-elasticsearch#81]
I have customized the toSearchableArray method of the models I am sending over to elasticsearch, so that they only contain relevant columns, and they also contain some common columns to make it easier to parse the search results. Here is the entire search related portion of the model:

`use Searchable;
    public function searchableAs()
    {
        return 'journals';
    }

    public function toSearchableArray()
    {
        (!empty($this->employee)) ? $employee = $this->employee->PayrollName : $employee = "";
        (!empty($this->supervisor)) ? $supervisor = $this->supervisor->PayrollName : $supervisor = "";
        (!empty($this->location)) ? $customer = $this->location->Customer : $customer = "";

        $array = array( 
            "Date" => Carbon::parse($this->Date)->format('Y-m-d'),
            "Definition" => $this->Definition,
            "Details" => $this->Details,
            'Employee' => $employee,
            'Supervisor' => $supervisor,
            'Customer' => $customer,
            'SEARCHdate' => Carbon::parse($this->Date)->format('Y-m-d'),
            'SEARCHtitle' => 'Journal - '.$employee.' ('.Carbon::parse($this->Date)->format('Y-m-d').')',
            'SEARCHurl' => '/journals/records/'.$this->id,
            'SEARCHempid' => $this->EmpID
        );

        return $array;
    }`

If I use something like dejavu to peak at the actual elasticsearch index named "journals", I can see that it is populated correctly with the chosen & additional columns. However, when I search that index, it does not return the columns contained in the index, but a full instance of the original model:

`$searchResults = Mixed::search(Input::get('query'))
                ->within(implode(',', [
                        (new Journal())->searchableAs(),
                        (new CorrectiveAction())->searchableAs(),
                    ]))
                ->orderBy('SEARCHdate', 'desc')
                ->paginate(10);`

Is this expected behavior? If it is, is it possible to change what gets returned by elasticsearch? I was hoping that it would be the exact same schema that I sent to it.

Thank you.

**Comment by bsaunders73** [comment]
I have done some additional research, and can close this:

1. Yes, it is expected behavior, and can be changed by using the raw method.
2. If you would like to paginate results while returning raw data, use the paginateRaw method.

**Comment by matchish** [comment]
Also, you can implement your own `HitsIteratorAggregate` and bind it in your service provider
https://github.com/matchish/laravel-scout-elasticsearch#working-with-results
