### ISSUE TITLE
Routing meta-field to use join datatype

### ISSUE THREAD

**Issue by burakcakirel** [matchish/laravel-scout-elasticsearch#90]
Need to add Routing meta-field to be able to use join datatype.
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html#CO163-1

Here is the quick solution by adding the following line after https://github.com/matchish/laravel-scout-elasticsearch/blob/v3.0.1/src/ElasticSearch/Params/Bulk.php#L49
https://github.com/matchish/laravel-scout-elasticsearch/blob/v3.0.1/src/ElasticSearch/Params/Bulk.php#L69

`'routing' => false === empty($model->routing) ? $model->routing : $model->getScoutKey(),`

So, we can define an accessor in our models:
https://laravel.com/docs/6.x/eloquent-mutators#defining-an-accessor

Any ideas? I'm ready to open a PR.

**Comment by matchish** [comment]
Thanks for the help! Looking forward to your quick solution implementation.

**Comment by matchish** [comment]
And could you please add `TODO` comment `Add ability to extend payload without modifying the class`.  Thanks!

**Comment by matchish** [comment]
Done
